package com.recettealarm.app;
import android.app.*;import android.content.*;import android.database.*;import android.graphics.Typeface;import android.os.*;import android.widget.*;import java.util.*;

public class ShoppingActivity extends Activity{DB db;LinearLayout root,box;Spinner recipeSpin;ArrayList<Long> recipeIds=new ArrayList<>();ArrayList<CheckBox> checks=new ArrayList<>();long selected=0;
 public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);draw();}
 void draw(){root=UI.root(this);Button back=UI.whiteBtn(this,"← Retour");root.addView(back);back.setOnClickListener(v->finish());root.addView(UI.tv(this,"Liste de courses",30,Typeface.BOLD));root.addView(UI.muted(this,"Choisis une recette, coche ce que tu as déjà, puis exporte seulement ce qui manque.",15));recipeSpin=new Spinner(this);loadRecipes();root.addView(recipeSpin);Button load=UI.btn(this,"Afficher les ingrédients");root.addView(load);load.setOnClickListener(v->renderIngredients());box=UI.section(this);root.addView(box);Button share=UI.oliveBtn(this,"Partager ce qui manque");root.addView(share);share.setOnClickListener(v->shareMissing());Button all=UI.whiteBtn(this,"Exporter liste complète");root.addView(all);all.setOnClickListener(v->share(db.shoppingListForRecipe(selected,false,new HashSet<Long>())));renderIngredients();}
 void loadRecipes(){ArrayList<String> titles=new ArrayList<>();Cursor c=db.recipes();while(c.moveToNext()){recipeIds.add(c.getLong(c.getColumnIndexOrThrow("id")));titles.add(c.getString(c.getColumnIndexOrThrow("title")));}c.close();if(recipeIds.size()==0){recipeIds.add(0L);titles.add("Aucune recette");}long wanted=getIntent().getLongExtra("recipe_id",0);selected=wanted>0?wanted:recipeIds.get(0);recipeSpin.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,titles));int pos=recipeIds.indexOf(selected);if(pos>=0)recipeSpin.setSelection(pos);recipeSpin.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,android.view.View v,int pos,long id){selected=recipeIds.get(pos);renderIngredients();}public void onNothingSelected(android.widget.AdapterView<?> p){}});}
 void renderIngredients(){if(box==null||selected==0)return;box.removeAllViews();checks.clear();box.addView(UI.tv(this,"Coche ce que tu as déjà",20,Typeface.BOLD));Cursor c=db.ingredients(selected);int n=0;while(c.moveToNext()){n++;CheckBox cb=new CheckBox(this);cb.setText(c.getString(2)+"  •  "+c.getString(3)+" "+c.getString(4));cb.setTextSize(17);cb.setTextColor(UI.dark);cb.setPadding(0,UI.dp(this,8),0,UI.dp(this,8));cb.setTag(c.getLong(0));checks.add(cb);box.addView(cb);}c.close();if(n==0)box.addView(UI.smallCard(this,"Aucun ingrédient dans cette recette."));}
 void shareMissing(){HashSet<Long> have=new HashSet<>();for(CheckBox cb:checks)if(cb.isChecked())have.add((Long)cb.getTag());share(db.shoppingListForRecipe(selected,true,have));}
 void share(String s){startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,s),"Partager"));}
}
