name: recette_alarm_pro

description: Application premium de recettes avec alarmes anti-brulure.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  vibration: ^2.0.1

flutter:
  uses-material-design: true
