import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:vibration/vibration.dart';

final FlutterLocalNotificationsPlugin notifications = FlutterLocalNotificationsPlugin();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  const initAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');
  await notifications.initialize(const InitializationSettings(android: initAndroid));
  runApp(const RecetteAlarmApp());
}

class AppColors {
  static const bg = Color(0xFFF7F5EF);
  static const dark = Color(0xFF102B2B);
  static const green = Color(0xFF0F5A55);
  static const gold = Color(0xFFF5C75D);
  static const cream = Color(0xFFFFFBF2);
  static const muted = Color(0xFF77736B);
  static const red = Color(0xFFE85050);
}

class Recipe {
  String id, title, category, imagePath, difficulty, liquidNote;
  int minutes, servings, rating, temp;
  List<Ingredient> ingredients;
  List<CookingStep> steps;
  List<String> videos;
  bool favorite;
  Recipe({required this.id, required this.title, required this.category, this.imagePath='', this.difficulty='Facile', this.liquidNote='', this.minutes=30, this.servings=4, this.rating=5, this.temp=160, this.favorite=false, List<Ingredient>? ingredients, List<CookingStep>? steps, List<String>? videos}) : ingredients=ingredients??[], steps=steps??[], videos=videos??[];
  Map<String,dynamic> toJson()=>{'id':id,'title':title,'category':category,'imagePath':imagePath,'difficulty':difficulty,'liquidNote':liquidNote,'minutes':minutes,'servings':servings,'rating':rating,'temp':temp,'favorite':favorite,'ingredients':ingredients.map((e)=>e.toJson()).toList(),'steps':steps.map((e)=>e.toJson()).toList(),'videos':videos};
  factory Recipe.fromJson(Map<String,dynamic> j)=>Recipe(id:j['id'],title:j['title'],category:j['category'],imagePath:j['imagePath']??'',difficulty:j['difficulty']??'Facile',liquidNote:j['liquidNote']??'',minutes:j['minutes']??30,servings:j['servings']??4,rating:j['rating']??5,temp:j['temp']??160,favorite:j['favorite']??false,ingredients:(j['ingredients'] as List? ?? []).map((e)=>Ingredient.fromJson(e)).toList(),steps:(j['steps'] as List? ?? []).map((e)=>CookingStep.fromJson(e)).toList(),videos:List<String>.from(j['videos']??[]));
}
class Ingredient {String name, unit; double qty; bool have; Ingredient(this.name,this.qty,this.unit,{this.have=false}); Map<String,dynamic> toJson()=>{'name':name,'qty':qty,'unit':unit,'have':have}; factory Ingredient.fromJson(Map<String,dynamic> j)=>Ingredient(j['name'],(j['qty'] as num).toDouble(),j['unit'],have:j['have']??false);}
class CookingStep {String title,note; int minutes,temp; CookingStep(this.title,this.minutes,this.temp,this.note); Map<String,dynamic> toJson()=>{'title':title,'minutes':minutes,'temp':temp,'note':note}; factory CookingStep.fromJson(Map<String,dynamic> j)=>CookingStep(j['title'],j['minutes'],j['temp']??0,j['note']??'');}

class Store extends ChangeNotifier{
  List<Recipe> recipes=[];
  Future<void> load() async {final sp=await SharedPreferences.getInstance(); final raw=sp.getString('recipes'); if(raw==null){recipes=[sampleRecipe()]; await save();} else {recipes=(jsonDecode(raw) as List).map((e)=>Recipe.fromJson(e)).toList();} notifyListeners();}
  Future<void> save() async {final sp=await SharedPreferences.getInstance(); await sp.setString('recipes', jsonEncode(recipes.map((e)=>e.toJson()).toList())); notifyListeners();}
  void upsert(Recipe r){final i=recipes.indexWhere((e)=>e.id==r.id); if(i>=0){recipes[i]=r;}else{recipes.add(r);} save();}
  void delete(String id){recipes.removeWhere((e)=>e.id==id); save();}
}
Recipe sampleRecipe()=>Recipe(id:'r1',title:'Tajine Poulet aux Olives',category:'Tajines',minutes:45,servings:4,rating:5,temp:160,liquidNote:'0.7 L / environ 3 verres et demi',videos:['https://youtube.com'],ingredients:[Ingredient('Poulet fermier',1.5,'kg'),Ingredient('Olives vertes',1,'verre'),Ingredient('Oignons',2,'pièces'),Ingredient('Eau',0.7,'L'),Ingredient('Safran',1,'pincée')],steps:[CookingStep('Faire revenir le poulet dans l’huile d’olive',10,160,'Remuer et vérifier le feu'),CookingStep('Ajouter oignons, épices et eau',20,180,'Vérifier l’eau pour éviter que la sauce sèche'),CookingStep('Ajouter les olives et réduire le feu',15,120,'Baisser le feu au minimum')]);

class RecetteAlarmApp extends StatefulWidget{const RecetteAlarmApp({super.key});@override State<RecetteAlarmApp> createState()=>_RecetteAlarmAppState();}
class _RecetteAlarmAppState extends State<RecetteAlarmApp>{final store=Store();@override void initState(){super.initState();store.load();}@override Widget build(BuildContext context)=>AnimatedBuilder(animation:store,builder:(_,__)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Recette Alarm',theme:ThemeData(useMaterial3:true,fontFamily:'Roboto',scaffoldBackgroundColor:AppColors.bg,colorScheme:ColorScheme.fromSeed(seedColor:AppColors.green)),home:HomePage(store:store)));}

class HomePage extends StatefulWidget{final Store store; const HomePage({super.key,required this.store});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{int tab=0; String q='';
  @override Widget build(BuildContext context){final pages=[home(),ShoppingPage(store:widget.store),EditRecipePage(store:widget.store),SettingsPage(store:widget.store)];return Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:bottomNav());}
  Widget home(){final list=widget.store.recipes.where((r)=>r.title.toLowerCase().contains(q.toLowerCase())||r.category.toLowerCase().contains(q.toLowerCase())).toList();return ListView(padding:const EdgeInsets.fromLTRB(20,18,20,110),children:[header(),const SizedBox(height:18),search(),const SizedBox(height:16),quickActions(),const SizedBox(height:22),sectionTitle('Catégories','Voir tout'),const SizedBox(height:12),categories(),const SizedBox(height:14),stats(),const SizedBox(height:24),sectionTitle('Recettes populaires',''),const SizedBox(height:12),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:list.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,mainAxisSpacing:18,crossAxisSpacing:16,childAspectRatio:.66),itemBuilder:(_,i)=>recipeCard(list[i]))]);}
  Widget header()=>Row(children:[roundIcon(Icons.menu,(){showMenuSheet();}),const SizedBox(width:16),Expanded(child:Text('Bonjour Chef 👋\nQue cuisine-t-on aujourd’hui ?',style:TextStyle(fontSize:31,height:1.15,fontWeight:FontWeight.w900,color:AppColors.dark))),roundIcon(Icons.notifications_none,(){})]);
  Widget search()=>Container(decoration:softBox(30),padding:const EdgeInsets.symmetric(horizontal:16),child:TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(border:InputBorder.none,icon:Icon(Icons.search),hintText:'Rechercher recette, ingrédient...')));
  Widget quickActions()=>Row(children:[chip('Scan',Icons.camera_alt,(){}),chip('Courses',Icons.shopping_cart,()=>setState(()=>tab=1)),chip('Mesures',Icons.straighten,()=>showConverter())]);
  Widget categories()=>SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:['Tous','Tajines','Gâteaux','Plats','Desserts','Jus'].map((e)=>Padding(padding:const EdgeInsets.only(right:10),child:Container(padding:const EdgeInsets.symmetric(horizontal:18,vertical:14),decoration:BoxDecoration(color:e=='Tous'?AppColors.green:Colors.white,borderRadius:BorderRadius.circular(26),boxShadow:shadow()),child:Text('${e=='Tous'?'🔥 ':''}$e',style:TextStyle(color:e=='Tous'?Colors.white:AppColors.dark,fontWeight:FontWeight.w800,fontSize:16))))).toList()));
  Widget stats(){final total=widget.store.recipes.length;final fav=widget.store.recipes.where((e)=>e.favorite).length;final min=widget.store.recipes.fold<int>(0,(a,b)=>a+b.minutes);return Row(children:[stat('🍽️','$total','Recettes'),stat('❤️','$fav','Favoris'),stat('⏱️','${min~/60}h${(min%60).toString().padLeft(2,'0')}','Temps')]);}
  Widget recipeCard(Recipe r)=>GestureDetector(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>DetailPage(store:widget.store,recipe:r))),child:Container(decoration:softBox(28),clipBehavior:Clip.antiAlias,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Stack(children:[Positioned.fill(child:HeroImage(r: r, compact:true)),Positioned(left:10,bottom:10,child:pill('⏱ ${r.minutes} min',AppColors.green,Colors.white)),Positioned(right:8,bottom:5,child:IconButton(onPressed:(){r.favorite=!r.favorite;widget.store.save();},icon:Icon(r.favorite?Icons.favorite:Icons.favorite_border,color:AppColors.red,size:30))) ])),Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(r.category,style:const TextStyle(color:AppColors.green,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text(r.title,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:7),Text('👥 ${r.servings} pers.   ⭐ ${r.rating}/5',style:const TextStyle(color:AppColors.muted,fontSize:14))]))])));
  Widget bottomNav()=>Container(margin:const EdgeInsets.fromLTRB(20,0,20,18),padding:const EdgeInsets.symmetric(vertical:10),decoration:softBox(34),child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[nav(0,Icons.home,'Accueil'),nav(1,Icons.shopping_cart,'Courses'),nav(2,Icons.add_circle,'Ajouter'),nav(3,Icons.settings,'Réglages')]));
  Widget nav(int i,IconData ic,String t)=>InkWell(onTap:()=>setState(()=>tab=i),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(ic,color:tab==i?AppColors.green:AppColors.muted),Text(t,style:TextStyle(fontWeight:FontWeight.w800,color:tab==i?AppColors.green:AppColors.dark))]));
  void showMenuSheet()=>showModalBottomSheet(context:context,backgroundColor:Colors.transparent,builder:(_)=>Container(padding:const EdgeInsets.all(20),decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.vertical(top:Radius.circular(32))),child:Column(mainAxisSize:MainAxisSize.min,children:[menu('Toutes les recettes',Icons.restaurant,()=>Navigator.pop(context)),menu('Favoris',Icons.favorite,()=>Navigator.pop(context)),menu('Liste de courses',Icons.shopping_cart,(){Navigator.pop(context);setState(()=>tab=1);}),menu('Nouvelle recette',Icons.add,(){Navigator.pop(context);setState(()=>tab=2);}),menu('Paramètres',Icons.settings,(){Navigator.pop(context);setState(()=>tab=3);})])));
  Widget menu(String t,IconData i,VoidCallback on)=>ListTile(leading:Icon(i,color:AppColors.green),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w800)),onTap:on);
  void showConverter()=>showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Convertisseur mesures'),content:const Text('1 litre ≈ 5 verres de 200 ml\n1 c. soupe ≈ 15 ml\n1 c. café ≈ 5 ml\n1 verre farine ≈ 160 g'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('OK'))]));
  Widget sectionTitle(String a,String b)=>Row(children:[Expanded(child:Text(a,style:const TextStyle(fontSize:29,fontWeight:FontWeight.w900,color:AppColors.dark))),if(b.isNotEmpty)Text(b,style:const TextStyle(fontWeight:FontWeight.w900,color:AppColors.green))]);
  Widget chip(String t,IconData i,VoidCallback on)=>Expanded(child:Padding(padding:const EdgeInsets.only(right:8),child:InkWell(onTap:on,child:Container(padding:const EdgeInsets.symmetric(vertical:12),decoration:softBox(24),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(i,size:18,color:AppColors.green),const SizedBox(width:5),Text(t,style:const TextStyle(fontWeight:FontWeight.w900))])))));
  Widget stat(String e,String n,String l)=>Expanded(child:Container(margin:const EdgeInsets.only(right:6),padding:const EdgeInsets.all(14),decoration:softBox(24),child:Column(children:[Text(e),Text(n,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(l,style:const TextStyle(fontWeight:FontWeight.w700))])));
}

class DetailPage extends StatelessWidget{final Store store; final Recipe recipe; const DetailPage({super.key,required this.store,required this.recipe});@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,16,20,110),children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[roundIcon(Icons.arrow_back,()=>Navigator.pop(context)),roundIcon(recipe.favorite?Icons.favorite:Icons.favorite_border,(){recipe.favorite=!recipe.favorite;store.save();})]),const SizedBox(height:22),HeroImage(r:recipe,height:260),const SizedBox(height:18),Center(child:Text(recipe.category,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16))),Center(child:Text(recipe.title,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:34,height:1.1))),const SizedBox(height:8),Center(child:Text('⭐ ${recipe.rating}/5',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:AppColors.gold))),const SizedBox(height:14),Row(children:[metric('⏱', '${recipe.minutes}\nmin'),metric('👥','${recipe.servings}\npers.'),metric('🔥',recipe.difficulty),metric('🌡','${recipe.temp}°C')]),const SizedBox(height:14),card(Text('💧 Liquide conseillé : ${recipe.liquidNote.isEmpty?'à définir':recipe.liquidNote}\n1 litre ≈ 5 verres de 200 ml',style:const TextStyle(fontSize:18,height:1.45))),const SizedBox(height:16),bigButton('▶ Démarrer la cuisine',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>CookingPage(recipe:recipe)))),const SizedBox(height:10),Row(children:[Expanded(child:outlineButton('Modifier',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>EditRecipePage(store:store,recipe:recipe))))),const SizedBox(width:8),Expanded(child:outlineButton('Courses',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ShoppingPage(store:store,recipe:recipe)))))]),title('Vidéos'),...recipe.videos.map((v)=>card(ListTile(leading:const Icon(Icons.movie,color:AppColors.green),title:Text(v,maxLines:1,overflow:TextOverflow.ellipsis),onTap:()=>launchUrl(Uri.parse(v))))),title('Ingrédients'),card(Column(children:recipe.ingredients.map((i)=>ListTile(leading:const Icon(Icons.circle,size:8,color:AppColors.gold),title:Text(i.name),trailing:Text('${fmt(i.qty)} ${i.unit}',style:const TextStyle(fontWeight:FontWeight.w900)))).toList())),title('Directions anti-brûlure'),...recipe.steps.asMap().entries.map((e)=>card(ListTile(title:Text('Étape ${e.key+1}  •  ${e.value.minutes} min  •  ${e.value.temp}°C',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${e.value.title}\n⚠ ${e.value.note}',style:const TextStyle(fontWeight:FontWeight.w700,height:1.45)))))])));}

class CookingPage extends StatefulWidget{final Recipe recipe; const CookingPage({super.key,required this.recipe});@override State<CookingPage> createState()=>_CookingPageState();}
class _CookingPageState extends State<CookingPage>{int idx=0,remaining=0,total=1;Timer? timer;bool running=false;@override void initState(){super.initState();setStep();}void setStep(){final m=widget.recipe.steps.isEmpty?1:widget.recipe.steps[idx].minutes;remaining=m*60;total=remaining;}void start(){timer?.cancel();running=true;timer=Timer.periodic(const Duration(seconds:1),(t){if(remaining<=0){t.cancel();alarm();}else setState(()=>remaining--);});setState((){});}void pause(){timer?.cancel();setState(()=>running=false);}Future<void> alarm()async{running=false;await Vibration.vibrate(duration:1200);const details=NotificationDetails(android:AndroidNotificationDetails('alarm','Alarmes cuisson',importance:Importance.max,priority:Priority.high,playSound:true,enableVibration:true,fullScreenIntent:true));await notifications.show(99,'Temps écoulé !',widget.recipe.steps[idx].note,details);if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>AlarmScreen(note:widget.recipe.steps[idx].note,onMore:(){Navigator.pop(context);setState(()=>remaining=300);start();})));} @override void dispose(){timer?.cancel();super.dispose();}
  @override Widget build(BuildContext context){final step=widget.recipe.steps.isEmpty?CookingStep('Aucune étape',1,0,''):widget.recipe.steps[idx];final p=remaining/total;return Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[Row(children:[roundIcon(Icons.arrow_back,()=>Navigator.pop(context)),const Spacer(),Text('Étape ${idx+1}/${widget.recipe.steps.length}',style:const TextStyle(fontWeight:FontWeight.w900))]),const SizedBox(height:30),CustomPaint(size:const Size(280,280),painter:RingPainter(p),child:SizedBox(width:280,height:280,child:Center(child:Text('${(remaining~/60).toString().padLeft(2,'0')}:${(remaining%60).toString().padLeft(2,'0')}',style:const TextStyle(fontSize:54,fontWeight:FontWeight.w300))))),const SizedBox(height:24),Text(step.title,textAlign:TextAlign.center,style:const TextStyle(fontSize:27,fontWeight:FontWeight.w900)),const SizedBox(height:10),card(Text('⚠ ${step.note}\n🌡 ${step.temp}°C',style:const TextStyle(fontSize:18,height:1.5,fontWeight:FontWeight.w700))),const Spacer(),Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[circleBtn(running?Icons.pause:Icons.play_arrow,running?pause:start),circleBtn(Icons.stop,(){timer?.cancel();setStep();setState(()=>running=false);}),circleBtn(Icons.add,(){setState(()=>remaining+=300);})]),const SizedBox(height:16),bigButton('Étape suivante',(){timer?.cancel();if(idx<widget.recipe.steps.length-1){setState(()=>idx++);setStep();}else{Navigator.pop(context);}})]))));}}

class AlarmScreen extends StatelessWidget{final String note; final VoidCallback onMore; const AlarmScreen({super.key,required this.note,required this.onMore});@override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.dark,body:SafeArea(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.notifications_active,color:AppColors.gold,size:86),const SizedBox(height:20),const Text('TEMPS ÉCOULÉ !',style:TextStyle(color:Colors.white,fontSize:34,fontWeight:FontWeight.w900)),const SizedBox(height:18),card(Text('⚠ $note',textAlign:TextAlign.center,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,height:1.4))),const SizedBox(height:26),bigButton('J’ai vérifié le plat',()=>Navigator.pop(context)),const SizedBox(height:12),outlineButton('+5 minutes',onMore)]))));}

class ShoppingPage extends StatefulWidget{final Store store;final Recipe? recipe;const ShoppingPage({super.key,required this.store,this.recipe});@override State<ShoppingPage> createState()=>_ShoppingPageState();}
class _ShoppingPageState extends State<ShoppingPage>{@override Widget build(BuildContext context){final r=widget.recipe??(widget.store.recipes.isEmpty?null:widget.store.recipes.first);if(r==null)return const Center(child:Text('Aucune recette'));return Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.all(22),children:[title('Liste de courses'),Text(r.title,style:const TextStyle(color:AppColors.muted,fontWeight:FontWeight.w700)),const SizedBox(height:16),...r.ingredients.map((i)=>card(CheckboxListTile(value:i.have,title:Text(i.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${fmt(i.qty)} ${i.unit}'),onChanged:(v){setState(()=>i.have=v??false);widget.store.save();}))),const SizedBox(height:16),bigButton('Exporter les ingrédients manquants',(){final missing=r.ingredients.where((e)=>!e.have).map((e)=>'- ${e.name} : ${fmt(e.qty)} ${e.unit}').join('\n');showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('À acheter'),content:Text(missing.isEmpty?'Rien ne manque ✅':missing),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('OK'))]));})])));}}

class EditRecipePage extends StatefulWidget{final Store store;final Recipe? recipe;const EditRecipePage({super.key,required this.store,this.recipe});@override State<EditRecipePage> createState()=>_EditRecipePageState();}
class _EditRecipePageState extends State<EditRecipePage>{late Recipe r; final picker=ImagePicker();@override void initState(){super.initState();r=widget.recipe??Recipe(id:DateTime.now().millisecondsSinceEpoch.toString(),title:'Nouvelle recette',category:'Tajines');}
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.all(22),children:[title(widget.recipe==null?'Nouvelle recette':'Modifier recette'),HeroImage(r:r,height:180,onTap:pick),field('Titre',r.title,(v)=>r.title=v),field('Catégorie',r.category,(v)=>r.category=v),field('Temps minutes',r.minutes.toString(),(v)=>r.minutes=int.tryParse(v)??r.minutes,number:true),field('Personnes',r.servings.toString(),(v)=>r.servings=int.tryParse(v)??r.servings,number:true),field('Température °C',r.temp.toString(),(v)=>r.temp=int.tryParse(v)??r.temp,number:true),field('Liquide conseillé',r.liquidNote,(v)=>r.liquidNote=v),bigButton('Enregistrer',(){widget.store.upsert(r);Navigator.pop(context);})])));Widget field(String l,String v,Function(String) on,{bool number=false})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(initialValue:v,keyboardType:number?TextInputType.number:TextInputType.text,onChanged:on,decoration:InputDecoration(labelText:l,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(20),borderSide:BorderSide.none))));Future<void> pick()async{final x=await picker.pickImage(source:ImageSource.gallery);if(x!=null)setState(()=>r.imagePath=x.path);}}
class SettingsPage extends StatelessWidget{final Store store;const SettingsPage({super.key,required this.store});@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.all(22),children:[title('Réglages'),card(const ListTile(leading:Icon(Icons.notifications,color:AppColors.green),title:Text('Alarmes fortes'),subtitle:Text('Sonnerie + vibration + notification'))),card(const ListTile(leading:Icon(Icons.straighten,color:AppColors.green),title:Text('Unités'),subtitle:Text('g, kg, ml, L, verre, cuillères'))),card(const ListTile(leading:Icon(Icons.dark_mode,color:AppColors.green),title:Text('Apparence'),subtitle:Text('Thème premium clair')))])));}

class HeroImage extends StatelessWidget{final Recipe r;final double height;final bool compact;final VoidCallback? onTap;const HeroImage({super.key,required this.r,this.height=170,this.compact=false,this.onTap});@override Widget build(BuildContext context)=>GestureDetector(onTap:onTap,child:Container(height:height,decoration:BoxDecoration(borderRadius:BorderRadius.circular(32),gradient:const LinearGradient(colors:[Color(0xFFFFF4CF),Color(0xFFE6F0E8)])),clipBehavior:Clip.antiAlias,child:r.imagePath.isNotEmpty?Image.file(File(r.imagePath),fit:BoxFit.cover):CustomPaint(painter:FoodPainter(),child:Center(child:Text(compact?'':r.title,textAlign:TextAlign.center,style:const TextStyle(color:AppColors.green,fontWeight:FontWeight.w900,fontSize:18))))));}
class FoodPainter extends CustomPainter{ @override void paint(Canvas c,Size s){final p=Paint()..color=Colors.white.withOpacity(.65);c.drawCircle(Offset(s.width*.5,s.height*.42),s.shortestSide*.22,p);p.color=AppColors.green;p.style=PaintingStyle.stroke;p.strokeWidth=5;c.drawCircle(Offset(s.width*.5,s.height*.42),s.shortestSide*.16,p);final tp=TextPainter(text:const TextSpan(text:'🥘',style:TextStyle(fontSize:42)),textDirection:TextDirection.ltr)..layout();tp.paint(c,Offset(s.width/2-tp.width/2,s.height*.42-tp.height/2));} @override bool shouldRepaint(covariant CustomPainter oldDelegate)=>false;}
class RingPainter extends CustomPainter{final double progress;RingPainter(this.progress);@override void paint(Canvas c,Size s){final center=Offset(s.width/2,s.height/2);final r=s.width/2-14;final base=Paint()..color=Colors.white..strokeWidth=18..style=PaintingStyle.stroke..strokeCap=StrokeCap.round;c.drawCircle(center,r,base);final p=Paint()..color=AppColors.gold..strokeWidth=18..style=PaintingStyle.stroke..strokeCap=StrokeCap.round;c.drawArc(Rect.fromCircle(center:center,radius:r),-1.57,6.28*progress,false,p);}@override bool shouldRepaint(covariant RingPainter oldDelegate)=>oldDelegate.progress!=progress;}

BoxDecoration softBox(double radius)=>BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(radius),boxShadow:shadow());List<BoxShadow> shadow()=>[BoxShadow(color:Colors.black.withOpacity(.08),blurRadius:16,offset:const Offset(0,8))];Widget roundIcon(IconData i,VoidCallback on)=>InkWell(onTap:on,child:Container(width:62,height:62,decoration:softBox(24),child:Icon(i,color:AppColors.dark,size:28)));Widget pill(String t,Color bg,Color fg)=>Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:9),decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(20)),child:Text(t,style:TextStyle(color:fg,fontWeight:FontWeight.w900)));Widget metric(String a,String b)=>Expanded(child:Container(margin:const EdgeInsets.only(right:8),padding:const EdgeInsets.symmetric(vertical:15),decoration:BoxDecoration(color:AppColors.gold.withOpacity(.9),borderRadius:BorderRadius.circular(28)),child:Column(children:[Text(a),Text(b,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16))])));Widget card(Widget child)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(14),decoration:softBox(24),child:child);Widget bigButton(String t,VoidCallback on)=>ElevatedButton(onPressed:on,style:ElevatedButton.styleFrom(backgroundColor:AppColors.gold,foregroundColor:AppColors.dark,elevation:8,padding:const EdgeInsets.symmetric(vertical:18),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(28))),child:Center(child:Text(t,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))));Widget outlineButton(String t,VoidCallback on)=>OutlinedButton(onPressed:on,style:OutlinedButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:16),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24))),child:Text(t,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17,color:AppColors.dark)));Widget title(String t)=>Padding(padding:const EdgeInsets.only(top:16,bottom:10),child:Text(t,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:AppColors.dark)));Widget circleBtn(IconData i,VoidCallback on)=>InkWell(onTap:on,child:Container(width:72,height:72,decoration:softBox(36),child:Icon(i,size:34,color:AppColors.green)));String fmt(double n)=>n==n.roundToDouble()?n.toInt().toString():n.toString();
