package com.recettealarm.app;
import android.content.*;import android.database.*;import android.database.sqlite.*;import java.util.*;
public class DB extends SQLiteOpenHelper{public DB(Context c){super(c,"recette_alarm.db",null,3);}public void onCreate(SQLiteDatabase d){schema(d);seed(d);}public void onUpgrade(SQLiteDatabase d,int o,int n){try{d.execSQL("ALTER TABLE recipes ADD COLUMN image TEXT");}catch(Exception e){}try{d.execSQL("ALTER TABLE recipes ADD COLUMN rating INT DEFAULT 0");}catch(Exception e){}try{d.execSQL("ALTER TABLE recipes ADD COLUMN water_liters TEXT");}catch(Exception e){}try{d.execSQL("ALTER TABLE steps ADD COLUMN temperature INT DEFAULT 0");}catch(Exception e){}try{d.execSQL("ALTER TABLE steps ADD COLUMN media TEXT");}catch(Exception e){}}
 void schema(SQLiteDatabase d){d.execSQL("CREATE TABLE recipes(id INTEGER PRIMARY KEY,title TEXT,category TEXT,servings INT,time INT,video TEXT,fav INT,created TEXT,image TEXT,rating INT,water_liters TEXT)");d.execSQL("CREATE TABLE ingredients(id INTEGER PRIMARY KEY,recipe_id INT,name TEXT,qty TEXT,unit TEXT,ord INT)");d.execSQL("CREATE TABLE steps(id INTEGER PRIMARY KEY,recipe_id INT,ord INT,description TEXT,duration INT,alarm INT,note TEXT,temperature INT,media TEXT)");}
 void seed(SQLiteDatabase d){ContentValues r=new ContentValues();r.put("title","Tajine Poulet aux Olives");r.put("category","Tajines");r.put("servings",4);r.put("time",45);r.put("fav",1);r.put("created","now");r.put("rating",5);r.put("water_liters","0.7");long id=d.insert("recipes",null,r);String[][] ing={{"Poulet fermier","1.5","kg"},{"Olives vertes","1","verre"},{"Oignons","2","pièce"},{"Eau","0.7","litre"},{"Safran","1","pincée"}};for(int i=0;i<ing.length;i++)addIng(d,id,ing[i][0],ing[i][1],ing[i][2],i);String[][] st={{"Faire revenir le poulet dans l'huile d'olive.","10","Remuer et vérifier le feu","160"},{"Ajouter oignons, épices et eau.","20","Vérifier l'eau","180"},{"Ajouter les olives et réduire le feu.","15","Baisser le feu au minimum","120"}};for(int i=0;i<st.length;i++)addStep(d,id,i+1,st[i][0],Integer.parseInt(st[i][1]),st[i][2],Integer.parseInt(st[i][3]),"");}
 void addIng(SQLiteDatabase d,long rid,String n,String q,String u,int ord){ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("name",n);v.put("qty",q);v.put("unit",u);v.put("ord",ord);d.insert("ingredients",null,v);}void addStep(SQLiteDatabase d,long rid,int ord,String desc,int min,String note,int temp,String media){ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("ord",ord);v.put("description",desc);v.put("duration",min);v.put("alarm",1);v.put("note",note);v.put("temperature",temp);v.put("media",media);d.insert("steps",null,v);} 
 Cursor recipes(){return getReadableDatabase().rawQuery("SELECT * FROM recipes ORDER BY id DESC",null);}Cursor one(long id){return getReadableDatabase().rawQuery("SELECT * FROM recipes WHERE id=?",new String[]{id+""});}Cursor ingredients(long id){return getReadableDatabase().rawQuery("SELECT * FROM ingredients WHERE recipe_id=? ORDER BY ord,id",new String[]{id+""});}Cursor steps(long id){return getReadableDatabase().rawQuery("SELECT * FROM steps WHERE recipe_id=? ORDER BY ord,id",new String[]{id+""});}
 long saveRecipe(long id,String title,String cat,int servings,int time,String video,String image,int rating,String water){ContentValues v=new ContentValues();v.put("title",title);v.put("category",cat);v.put("servings",servings);v.put("time",time);v.put("video",video);v.put("image",image);v.put("rating",rating);v.put("water_liters",water);v.put("created",new Date().toString());if(id>0){getWritableDatabase().update("recipes",v,"id=?",new String[]{id+""});return id;}return getWritableDatabase().insert("recipes",null,v);} 
 void addIng(long rid,String n,String q,String u){Cursor c=ingredients(rid);int ord=c.getCount()+1;c.close();ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("name",n);v.put("qty",q);v.put("unit",u);v.put("ord",ord);getWritableDatabase().insert("ingredients",null,v);}void addStep(long rid,String d,int min,String note,int temp,String media){Cursor c=steps(rid);int ord=c.getCount()+1;c.close();ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("ord",ord);v.put("description",d);v.put("duration",min);v.put("alarm",1);v.put("note",note);v.put("temperature",temp);v.put("media",media);getWritableDatabase().insert("steps",null,v);}void del(String table,long id){getWritableDatabase().delete(table,"id=?",new String[]{id+""});}
 void clearChildren(long rid){getWritableDatabase().delete("ingredients","recipe_id=?",new String[]{rid+""});getWritableDatabase().delete("steps","recipe_id=?",new String[]{rid+""});}
 String shoppingList(){Cursor c=getReadableDatabase().rawQuery("SELECT LOWER(name),name,qty,unit FROM ingredients",null);LinkedHashMap<String,String> map=new LinkedHashMap<>();while(c.moveToNext()){String key=c.getString(0)+"|"+c.getString(3);String old=map.get(key);String line="• "+c.getString(1)+" - "+c.getString(2)+" "+c.getString(3);map.put(key,old==null?line:old+" + "+c.getString(2)+" "+c.getString(3));}c.close();StringBuilder s=new StringBuilder("Liste de courses Recette Alarm:\n\n");for(String v:map.values())s.append(v).append('\n');s.append("\nConversions utiles:\n• 1 litre = 1000 ml\n• 1 verre ≈ 200 ml\n• 1 litre ≈ 5 verres\n• 1 cuillère soupe ≈ 15 ml\n• 1 cuillère café ≈ 5 ml\n");return s.toString();}
}
