package com.recettealarm.app;
import android.content.*;import android.database.*;import android.database.sqlite.*;import java.util.*;
public class DB extends SQLiteOpenHelper{public DB(Context c){super(c,"recette_alarm.db",null,4);}public void onCreate(SQLiteDatabase d){schema(d);seed(d);}public void onUpgrade(SQLiteDatabase d,int o,int n){try{d.execSQL("ALTER TABLE recipes ADD COLUMN image TEXT");}catch(Exception e){}try{d.execSQL("ALTER TABLE recipes ADD COLUMN rating INT DEFAULT 0");}catch(Exception e){}try{d.execSQL("ALTER TABLE recipes ADD COLUMN water_liters TEXT");}catch(Exception e){}try{d.execSQL("ALTER TABLE recipes ADD COLUMN fav INT DEFAULT 0");}catch(Exception e){}try{d.execSQL("ALTER TABLE steps ADD COLUMN temperature INT DEFAULT 0");}catch(Exception e){}try{d.execSQL("ALTER TABLE steps ADD COLUMN media TEXT");}catch(Exception e){}}
 void schema(SQLiteDatabase d){d.execSQL("CREATE TABLE recipes(id INTEGER PRIMARY KEY,title TEXT,category TEXT,servings INT,time INT,video TEXT,fav INT DEFAULT 0,created TEXT,image TEXT,rating INT DEFAULT 0,water_liters TEXT)");d.execSQL("CREATE TABLE ingredients(id INTEGER PRIMARY KEY,recipe_id INT,name TEXT,qty TEXT,unit TEXT,ord INT)");d.execSQL("CREATE TABLE steps(id INTEGER PRIMARY KEY,recipe_id INT,ord INT,description TEXT,duration INT,alarm INT,note TEXT,temperature INT,media TEXT)");}
 void seed(SQLiteDatabase d){ContentValues r=new ContentValues();r.put("title","Tajine Poulet aux Olives");r.put("category","Tajines");r.put("servings",4);r.put("time",45);r.put("fav",1);r.put("created","now");r.put("rating",5);r.put("water_liters","0.7 L / environ 3 verres et demi");r.put("video","https://www.youtube.com/");long id=d.insert("recipes",null,r);String[][] ing={{"Poulet fermier","1.5","kg"},{"Olives vertes","1","verre"},{"Oignons","2","pièce"},{"Eau","0.7","litre"},{"Safran","1","pincée"}};for(int i=0;i<ing.length;i++)addIng(d,id,ing[i][0],ing[i][1],ing[i][2],i);String[][] st={{"Faire revenir le poulet dans l'huile d'olive.","10","Remuer et vérifier le feu","160"},{"Ajouter oignons, épices et eau.","20","Vérifier l'eau et éviter que la sauce sèche","180"},{"Ajouter les olives et réduire le feu.","15","Baisser le feu au minimum","120"}};for(int i=0;i<st.length;i++)addStep(d,id,i+1,st[i][0],Integer.parseInt(st[i][1]),st[i][2],Integer.parseInt(st[i][3]),"");}
 void addIng(SQLiteDatabase d,long rid,String n,String q,String u,int ord){ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("name",n);v.put("qty",q);v.put("unit",u);v.put("ord",ord);d.insert("ingredients",null,v);}void addStep(SQLiteDatabase d,long rid,int ord,String desc,int min,String note,int temp,String media){ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("ord",ord);v.put("description",desc);v.put("duration",min);v.put("alarm",1);v.put("note",note);v.put("temperature",temp);v.put("media",media);d.insert("steps",null,v);} 
 Cursor recipes(){return getReadableDatabase().rawQuery("SELECT * FROM recipes ORDER BY fav DESC,id DESC",null);}Cursor recipesByCategory(String cat){if(cat==null||cat.length()==0||cat.equals("Tous"))return recipes();return getReadableDatabase().rawQuery("SELECT * FROM recipes WHERE category LIKE ? ORDER BY fav DESC,id DESC",new String[]{"%"+cat+"%"});}Cursor one(long id){return getReadableDatabase().rawQuery("SELECT * FROM recipes WHERE id=?",new String[]{id+""});}Cursor ingredients(long id){return getReadableDatabase().rawQuery("SELECT * FROM ingredients WHERE recipe_id=? ORDER BY ord,id",new String[]{id+""});}Cursor steps(long id){return getReadableDatabase().rawQuery("SELECT * FROM steps WHERE recipe_id=? ORDER BY ord,id",new String[]{id+""});}
 long saveRecipe(long id,String title,String cat,int servings,int time,String video,String image,int rating,String water){ContentValues v=new ContentValues();v.put("title",empty(title)?"Recette sans nom":title);v.put("category",empty(cat)?"Autres":cat);v.put("servings",servings);v.put("time",time);v.put("video",video);v.put("image",image);v.put("rating",rating);v.put("water_liters",water);v.put("created",new Date().toString());if(id>0){getWritableDatabase().update("recipes",v,"id=?",new String[]{id+""});return id;}return getWritableDatabase().insert("recipes",null,v);} 
 void addIng(long rid,String n,String q,String u){Cursor c=ingredients(rid);int ord=c.getCount()+1;c.close();ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("name",n);v.put("qty",empty(q)?"1":q);v.put("unit",empty(u)?"pièce":u);v.put("ord",ord);getWritableDatabase().insert("ingredients",null,v);}void addStep(long rid,String d,int min,String note,int temp,String media){Cursor c=steps(rid);int ord=c.getCount()+1;c.close();ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("ord",ord);v.put("description",d);v.put("duration",Math.max(1,min));v.put("alarm",1);v.put("note",note);v.put("temperature",Math.max(0,temp));v.put("media",media);getWritableDatabase().insert("steps",null,v);}void del(String table,long id){getWritableDatabase().delete(table,"id=?",new String[]{id+""});}
 void deleteRecipe(long rid){getWritableDatabase().delete("ingredients","recipe_id=?",new String[]{rid+""});getWritableDatabase().delete("steps","recipe_id=?",new String[]{rid+""});getWritableDatabase().delete("recipes","id=?",new String[]{rid+""});}
 void clearChildren(long rid){getWritableDatabase().delete("ingredients","recipe_id=?",new String[]{rid+""});getWritableDatabase().delete("steps","recipe_id=?",new String[]{rid+""});}
 void fav(long rid,int fav){ContentValues v=new ContentValues();v.put("fav",fav);getWritableDatabase().update("recipes",v,"id=?",new String[]{rid+""});}
 int count(String table){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM "+table,null);int n=0;if(c.moveToFirst())n=c.getInt(0);c.close();return n;}
 String shoppingList(){Cursor c=getReadableDatabase().rawQuery("SELECT LOWER(name),name,qty,unit FROM ingredients ORDER BY name",null);LinkedHashMap<String,Double> nums=new LinkedHashMap<>();LinkedHashMap<String,String> names=new LinkedHashMap<>();ArrayList<String> raw=new ArrayList<>();while(c.moveToNext()){String name=c.getString(1),qty=c.getString(2),unit=c.getString(3);String key=c.getString(0)+"|"+unit;Double n=parse(qty);if(n!=null){nums.put(key,(nums.containsKey(key)?nums.get(key):0)+n);names.put(key,name+"|"+unit);}else raw.add("• "+name+" - "+qty+" "+unit);}c.close();StringBuilder s=new StringBuilder("Liste de courses Recette Alarm:\n\n");for(String k:nums.keySet()){String[] p=names.get(k).split("\\|");s.append("• ").append(cap(p[0])).append(" - ").append(fmt(nums.get(k))).append(" ").append(p.length>1?p[1]:"").append('\n');}for(String line:raw)s.append(line).append('\n');s.append("\nRepères liquides:\n• 1 litre = 1000 ml\n• 1 verre ≈ 200 ml\n• 1 litre ≈ 5 verres\n• 1 cuillère soupe ≈ 15 ml\n• 1 cuillère café ≈ 5 ml\n");return s.toString();}

 String shoppingListForRecipe(long rid, boolean onlyMissing, java.util.Set<Long> have){Cursor c=ingredients(rid);String title="Recette";Cursor r=one(rid);if(r.moveToFirst())title=r.getString(r.getColumnIndexOrThrow("title"));r.close();StringBuilder s=new StringBuilder();s.append(onlyMissing?"Ingrédients manquants - ":"Liste complète - ").append(title).append("\n\n");int n=0;while(c.moveToNext()){long id=c.getLong(0);if(onlyMissing&&have!=null&&have.contains(id))continue;n++;s.append("☐ ").append(c.getString(2)).append(" - ").append(c.getString(3)).append(" ").append(c.getString(4)).append('\n');}c.close();if(n==0)s.append("✅ Rien ne manque pour cette recette.\n");s.append("\nRepères utiles :\n• 1 litre = 1000 ml\n• 1 verre ≈ 200 ml, donc 1 L ≈ 5 verres\n• 1 c. soupe ≈ 15 ml\n• 1 c. café ≈ 5 ml\n");return s.toString();}
 String conversions(){return "Conversions rapides\n\nLiquides :\n• 0.25 L = 250 ml ≈ 1 verre + 1/4\n• 0.5 L = 500 ml ≈ 2 verres et demi\n• 1 L = 1000 ml ≈ 5 verres\n\nCuillères :\n• 1 c. soupe ≈ 15 ml\n• 1 c. café ≈ 5 ml\n\nFarine/Sucre approximatif :\n• 1 verre farine ≈ 120 g\n• 1 verre sucre ≈ 160 g\n• 1 verre huile ≈ 180 ml\n";}
 static boolean empty(String s){return s==null||s.trim().length()==0;}static Double parse(String s){try{return Double.parseDouble(s.trim().replace(",","."));}catch(Exception e){return null;}}static String fmt(double d){if(Math.abs(d-Math.round(d))<0.001)return ""+(long)Math.round(d);return String.format(java.util.Locale.US,"%.2f",d).replace(".00","");}static String cap(String s){return s.length()==0?s:s.substring(0,1).toUpperCase()+s.substring(1);} }
