package com.recettealarm.app;
import android.app.*;import android.content.*;import android.database.*;import android.graphics.Typeface;import android.net.*;import android.os.*;import android.widget.*;
public class DetailActivity extends Activity{long id;DB db;String videos="",title="Recette";public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);id=getIntent().getLongExtra("id",0);}public void onResume(){super.onResume();draw();}
 void draw(){LinearLayout r=UI.root(this);r.setPadding(UI.dp(this,16),UI.dp(this,15),UI.dp(this,16),UI.dp(this,30));Cursor c=db.one(id);String img="",cat="",water="";int time=0,serv=0,rat=0,fav=0;if(c.moveToFirst()){title=s(c,"title");cat=s(c,"category");videos=s(c,"video");img=s(c,"image");time=c.getInt(c.getColumnIndexOrThrow("time"));serv=c.getInt(c.getColumnIndexOrThrow("servings"));rat=c.getInt(c.getColumnIndexOrThrow("rating"));water=s(c,"water_liters");try{fav=c.getInt(c.getColumnIndexOrThrow("fav"));}catch(Exception e){}}c.close();LinearLayout top=UI.row(this);TextView back=UI.iconBtn(this,"‹");TextView heart=UI.iconBtn(this,fav==1?"♥":"♡");top.addView(back);top.addView(new Space(this),new LinearLayout.LayoutParams(0,1,1));top.addView(heart);r.addView(top);back.setOnClickListener(v->finish());int nf=fav==1?0:1;heart.setOnClickListener(v->{db.fav(id,nf);draw();});
  r.addView(UI.foodHero(this,img,250,iconFor(cat),title));r.addView(UI.center(this,cat,14,Typeface.BOLD));TextView t=UI.center(this,title,29,Typeface.BOLD);r.addView(t);TextView rating=UI.center(this,"⭐ "+rat+"/5",19,Typeface.BOLD);rating.setTextColor(UI.gold);r.addView(rating);
  LinearLayout stats=UI.row(this);stats.addView(info("⏱",time+"\nmin"),new LinearLayout.LayoutParams(0,-2,1));stats.addView(info("👥",serv+"\npers."),new LinearLayout.LayoutParams(0,-2,1));stats.addView(info("🔥","Facile"),new LinearLayout.LayoutParams(0,-2,1));stats.addView(info("🌡","Cuisson"),new LinearLayout.LayoutParams(0,-2,1));r.addView(stats);if(water!=null&&water.trim().length()>0)r.addView(UI.smallCard(this,"💧 Liquide conseillé : "+water+"\n1 litre ≈ 5 verres de 200 ml"));
  Button cook=UI.limeBtn(this,"▶ Démarrer la cuisine");r.addView(cook);cook.setOnClickListener(v->startActivity(new Intent(this,CookingActivity.class).putExtra("id",id)));LinearLayout actions=UI.row(this);Button edit=UI.whiteBtn(this,"Modifier");Button shop=UI.whiteBtn(this,"Courses");actions.addView(edit,new LinearLayout.LayoutParams(0,-2,1));actions.addView(shop,new LinearLayout.LayoutParams(0,-2,1));r.addView(actions);edit.setOnClickListener(v->startActivity(new Intent(this,EditRecipeActivity.class).putExtra("id",id)));shop.setOnClickListener(v->startActivity(new Intent(this,ShoppingActivity.class).putExtra("recipe_id",id)));addVideos(r);
  r.addView(UI.tv(this,"Ingrédients",24,Typeface.BOLD));LinearLayout ingBox=UI.section(this);Cursor i=db.ingredients(id);int count=0;while(i.moveToNext()){count++;TextView row=UI.smallCard(this,"• "+i.getString(2)+"     "+i.getString(3)+" "+i.getString(4));ingBox.addView(row);}i.close();if(count==0)ingBox.addView(UI.smallCard(this,"Aucun ingrédient encore."));r.addView(ingBox);
  r.addView(UI.tv(this,"Directions anti-brûlure",24,Typeface.BOLD));Cursor st=db.steps(id);int stepCount=0;while(st.moveToNext()){stepCount++;int temp=st.getInt(7);String card="Étape "+st.getInt(2)+"  •  "+st.getInt(4)+" min"+(temp>0?"  •  "+temp+"°C":"")+"\n"+st.getString(3)+"\n⚠ "+st.getString(6);r.addView(UI.card(this,card));}st.close();if(stepCount==0)r.addView(UI.smallCard(this,"Ajoute au moins une étape avant de lancer la cuisine."));}
 TextView info(String icon,String val){TextView v=UI.center(this,icon+"\n"+val,13,Typeface.BOLD);v.setBackground(UI.grad(UI.lime,UI.lime2,UI.dp(this,30)));v.setPadding(0,UI.dp(this,10),0,UI.dp(this,10));return v;}String iconFor(String c){if(c==null)return "🍽";if(c.contains("Taj"))return "🥘";if(c.contains("Gâteau"))return "🍰";if(c.contains("Jus"))return "🥤";if(c.contains("Pain"))return "🥖";return "🍽";}
 void addVideos(LinearLayout r){if(videos==null||videos.trim().length()==0)return;r.addView(UI.tv(this,"Vidéos",24,Typeface.BOLD));String[] lines=videos.split("\\n|,|;");int n=1;for(String raw:lines){String u=raw.trim();if(u.length()<5)continue;Button b=UI.whiteBtn(this,"🎥 Vidéo "+n);r.addView(b);b.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){UI.toast(this,"Lien vidéo invalide");}});n++;}}
 String s(Cursor c,String col){try{String x=c.getString(c.getColumnIndexOrThrow(col));return x==null?"":x;}catch(Exception e){return "";}}
}
