package com.recettealarm.app;
import android.app.*;import android.content.*;import android.database.*;import android.graphics.Typeface;import android.net.*;import android.os.*;import android.widget.*;
public class DetailActivity extends Activity{long id;DB db;String videos="",title="Recette";public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);id=getIntent().getLongExtra("id",0);draw();}
 void draw(){LinearLayout r=UI.root(this);Button back=UI.whiteBtn(this,"← Retour");r.addView(back);back.setOnClickListener(v->finish());Cursor c=db.one(id);String img="",cat="";int time=0,serv=0,rat=0;String water="";if(c.moveToFirst()){title=c.getString(c.getColumnIndexOrThrow("title"));cat=c.getString(c.getColumnIndexOrThrow("category"));videos=c.getString(c.getColumnIndexOrThrow("video"));img=c.getString(c.getColumnIndexOrThrow("image"));time=c.getInt(c.getColumnIndexOrThrow("time"));serv=c.getInt(c.getColumnIndexOrThrow("servings"));rat=c.getInt(c.getColumnIndexOrThrow("rating"));water=c.getString(c.getColumnIndexOrThrow("water_liters"));}c.close();r.addView(UI.image(this,img,190));r.addView(UI.tv(this,title,31,Typeface.BOLD));TextView stars=UI.tv(this,UI.stars(rat),22,Typeface.BOLD);stars.setTextColor(UI.gold);r.addView(stars);r.addView(UI.tv(this,cat+"   •   ⏱ "+time+" min   •   👥 "+serv+" pers.",16,Typeface.NORMAL));if(water!=null&&water.trim().length()>0)r.addView(UI.smallCard(this,"💧 Liquide conseillé : "+water+"\nRepère : 1 litre ≈ 5 verres de 200 ml"));
 Button cook=UI.btn(this,"▶ Démarrer la Cuisine");r.addView(cook);cook.setOnClickListener(v->startActivity(new Intent(this,CookingActivity.class).putExtra("id",id)));Button edit=UI.whiteBtn(this,"⚙ Modifier / Admin");r.addView(edit);edit.setOnClickListener(v->startActivity(new Intent(this,EditRecipeActivity.class).putExtra("id",id)));addVideos(r);
 r.addView(UI.tv(this,"Ingrédients",24,Typeface.BOLD));LinearLayout ingBox=UI.section(this);Cursor i=db.ingredients(id);int count=0;while(i.moveToNext()){count++;ingBox.addView(UI.smallCard(this,"• "+i.getString(2)+"     "+i.getString(3)+" "+i.getString(4)));}i.close();if(count==0)ingBox.addView(UI.smallCard(this,"Aucun ingrédient encore."));r.addView(ingBox);
 r.addView(UI.tv(this,"Étapes anti-brûlure",24,Typeface.BOLD));Cursor s=db.steps(id);int stepCount=0;while(s.moveToNext()){stepCount++;int temp=s.getInt(7);String t="Étape "+s.getInt(2)+"   •   ⏱ "+s.getInt(4)+" min"+(temp>0?"   •   🌡 "+temp+"°C":"")+"\n"+s.getString(3)+"\n⚠ "+s.getString(6);r.addView(UI.card(this,t));}s.close();if(stepCount==0)r.addView(UI.smallCard(this,"Ajoute au moins une étape avant de lancer la cuisine."));}
 void addVideos(LinearLayout r){if(videos==null||videos.trim().length()==0)return;String[] lines=videos.split("\\n|,|;");int n=1;for(String raw:lines){String u=raw.trim();if(u.length()<5)continue;Button b=UI.whiteBtn(this,"🎥 Ouvrir vidéo "+n);r.addView(b);b.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){UI.toast(this,"Lien vidéo invalide");}});n++;}}
}
