package com.recettealarm.app;
import android.app.*;import android.content.*;import android.database.*;import android.graphics.Typeface;import android.net.*;import android.os.*;import android.widget.*;
public class EditRecipeActivity extends Activity{DB db;EditText title,cat,serv,time,videos,water,rating,ing,qty,unit,step,min,note,temp,media;TextView photoLabel;String image="";long rid=0;static final int PICK=44;public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);rid=getIntent().getLongExtra("id",0);draw();if(rid>0)load();}
 void draw(){LinearLayout r=UI.root(this);Button back=UI.whiteBtn(this,"← Retour");r.addView(back);back.setOnClickListener(v->finish());r.addView(UI.tv(this,rid>0?"Modifier la recette":"Nouvelle Recette",30,Typeface.BOLD));r.addView(UI.tv(this,"Remplis la recette, puis ajoute ingrédients et étapes.",14,Typeface.NORMAL));
 r.addView(UI.tv(this,"Informations",22,Typeface.BOLD));title=UI.input(this,"Nom recette");cat=UI.input(this,"Catégorie : Tajines, Gâteaux...");serv=UI.number(this,"Nombre de personnes");time=UI.number(this,"Temps total minutes");water=UI.input(this,"Eau/liquide conseillé : ex 0.7 L ou 3 verres");rating=UI.number(this,"Rating 1 à 5");videos=UI.area(this,"Liens vidéos multiples : 1 lien par ligne");photoLabel=UI.smallCard(this,"📷 Aucune image sélectionnée");Button pick=UI.whiteBtn(this,"📷 Sélectionner image depuis téléphone");r.addView(title);r.addView(cat);r.addView(serv);r.addView(time);r.addView(water);r.addView(rating);r.addView(videos);r.addView(photoLabel);r.addView(pick);pick.setOnClickListener(v->pickImage());Button save=UI.btn(this,"💾 Enregistrer / Mettre à jour");r.addView(save);
 r.addView(UI.tv(this,"Ingrédient",22,Typeface.BOLD));ing=UI.input(this,"Nom ingrédient");qty=UI.input(this,"Quantité : ex 250");unit=UI.input(this,"Unité : g, kg, ml, litre, verre, cuillère...");r.addView(ing);r.addView(qty);r.addView(unit);Button ai=UI.oliveBtn(this,"+ Ajouter ingrédient");r.addView(ai);
 r.addView(UI.tv(this,"Étape anti-brûlure",22,Typeface.BOLD));step=UI.area(this,"Description étape");min=UI.number(this,"Durée minutes");temp=UI.number(this,"Température / degrés °C optionnel");note=UI.input(this,"Note sécurité : remuer, baisser le feu...");media=UI.input(this,"Lien image/vidéo étape optionnel");r.addView(step);r.addView(min);r.addView(temp);r.addView(note);r.addView(media);Button ast=UI.oliveBtn(this,"+ Ajouter étape");r.addView(ast);Button clear=UI.whiteBtn(this,"🧹 Réinitialiser ingrédients/étapes");r.addView(clear);
 save.setOnClickListener(v->{rid=db.saveRecipe(rid,val(title),val(cat),num(serv,4),num(time,30),val(videos),image,num(rating,0),val(water));UI.toast(this,"Recette enregistrée ✅");});ai.setOnClickListener(v->{ensure();if(val(ing).trim().length()==0)return;db.addIng(rid,val(ing),val(qty),val(unit));ing.setText("");qty.setText("");unit.setText("");UI.toast(this,"Ingrédient ajouté");});ast.setOnClickListener(v->{ensure();if(val(step).trim().length()==0)return;db.addStep(rid,val(step),num(min,5),val(note),num(temp,0),val(media));step.setText("");min.setText("");temp.setText("");note.setText("");media.setText("");UI.toast(this,"Étape ajoutée");});clear.setOnClickListener(v->{if(rid>0){db.clearChildren(rid);UI.toast(this,"Ingrédients et étapes supprimés");}});}
 void load(){Cursor c=db.one(rid);if(c.moveToFirst()){title.setText(c.getString(c.getColumnIndexOrThrow("title")));cat.setText(c.getString(c.getColumnIndexOrThrow("category")));serv.setText(""+c.getInt(c.getColumnIndexOrThrow("servings")));time.setText(""+c.getInt(c.getColumnIndexOrThrow("time")));videos.setText(c.getString(c.getColumnIndexOrThrow("video")));image=c.getString(c.getColumnIndexOrThrow("image"));rating.setText(""+c.getInt(c.getColumnIndexOrThrow("rating")));water.setText(c.getString(c.getColumnIndexOrThrow("water_liters")));if(image!=null&&image.length()>0)photoLabel.setText("📷 Image sélectionnée");}c.close();}
 void ensure(){if(rid==0)rid=db.saveRecipe(0,val(title),val(cat),num(serv,4),num(time,30),val(videos),image,num(rating,0),val(water));}
 void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK);}public void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}image=u.toString();photoLabel.setText("📷 Image sélectionnée ✅");}}
 String val(EditText e){return e.getText().toString();}int num(EditText e,int d){try{return (int)Float.parseFloat(val(e).trim());}catch(Exception x){return d;}}}
