package com.recettealarm.app;
import android.app.*;import android.content.*;import android.database.*;import android.graphics.Typeface;import android.net.*;import android.os.*;import android.widget.*;
public class EditRecipeActivity extends Activity{DB db;EditText title,cat,serv,time,videos,water,rating,ing,qty,unit,step,min,note,temp,media;TextView photoLabel;LinearLayout ingList,stepList;String image="";long rid=0;static final int PICK=44;public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);rid=getIntent().getLongExtra("id",0);draw();if(rid>0)load();refreshLists();}
 void draw(){LinearLayout r=UI.root(this);Button back=UI.whiteBtn(this,"← Retour");r.addView(back);back.setOnClickListener(v->finish());r.addView(UI.tv(this,rid>0?"Modifier / Admin":"Nouvelle recette",30,Typeface.BOLD));r.addView(UI.muted(this,"Sauvegarde les infos puis ajoute ingrédients et étapes.",14));
 LinearLayout info=UI.section(this);info.addView(UI.tv(this,"1. Informations recette",22,Typeface.BOLD));title=UI.input(this,"Nom recette");cat=UI.input(this,"Catégorie : Tajines, Gâteaux, Plats...");serv=UI.number(this,"Nombre de personnes");time=UI.number(this,"Temps total minutes");water=UI.input(this,"Liquide conseillé : ex 0.7 L / 3 verres");rating=UI.number(this,"Rating 1 à 5");videos=UI.area(this,"Plusieurs liens vidéos : 1 lien par ligne");photoLabel=UI.smallCard(this,"📷 Aucune image sélectionnée");Button pick=UI.whiteBtn(this,"📷 Sélectionner image depuis téléphone");info.addView(title);info.addView(cat);info.addView(serv);info.addView(time);info.addView(water);info.addView(rating);info.addView(videos);info.addView(photoLabel);info.addView(pick);r.addView(info);pick.setOnClickListener(v->pickImage());Button save=UI.btn(this,"💾 Enregistrer recette");r.addView(save);
 LinearLayout ingBox=UI.section(this);ingBox.addView(UI.tv(this,"2. Ingrédients",22,Typeface.BOLD));ingBox.addView(UI.muted(this,"Astuce : utilise g, kg, ml, litre, verre, cuillère, pièce.",13));ing=UI.input(this,"Nom ingrédient");qty=UI.input(this,"Quantité : ex 250");unit=UI.input(this,"Unité : g, kg, ml, litre, verre...");ingBox.addView(ing);ingBox.addView(qty);ingBox.addView(unit);Button ai=UI.oliveBtn(this,"+ Ajouter ingrédient");ingBox.addView(ai);ingList=new LinearLayout(this);ingList.setOrientation(LinearLayout.VERTICAL);ingBox.addView(ingList);r.addView(ingBox);
 LinearLayout stBox=UI.section(this);stBox.addView(UI.tv(this,"3. Étapes anti-brûlure",22,Typeface.BOLD));stBox.addView(UI.muted(this,"Chaque étape peut déclencher sonnerie + vibration + alerte.",13));step=UI.area(this,"Description étape");min=UI.number(this,"Durée minutes");temp=UI.number(this,"Température / degrés °C optionnel");note=UI.input(this,"Note sécurité : remuer, vérifier eau, baisser feu...");media=UI.input(this,"Lien image/vidéo étape optionnel");stBox.addView(step);stBox.addView(min);stBox.addView(temp);stBox.addView(note);stBox.addView(media);Button ast=UI.oliveBtn(this,"+ Ajouter étape");stBox.addView(ast);stepList=new LinearLayout(this);stepList.setOrientation(LinearLayout.VERTICAL);stBox.addView(stepList);r.addView(stBox);
 Button preview=UI.btn(this,"👀 Voir la recette");Button clear=UI.whiteBtn(this,"🧹 Réinitialiser ingrédients/étapes");Button del=UI.dangerBtn(this,"🗑 Supprimer recette");r.addView(preview);r.addView(clear);if(rid>0)r.addView(del);
 save.setOnClickListener(v->{saveRecipe();UI.toast(this,"Recette enregistrée ✅");});ai.setOnClickListener(v->{ensure();if(val(ing).trim().length()==0){UI.toast(this,"Ajoute le nom de l'ingrédient");return;}db.addIng(rid,val(ing),val(qty),val(unit));ing.setText("");qty.setText("");unit.setText("");refreshLists();});ast.setOnClickListener(v->{ensure();if(val(step).trim().length()==0){UI.toast(this,"Ajoute la description de l'étape");return;}db.addStep(rid,val(step),num(min,5),val(note),num(temp,0),val(media));step.setText("");min.setText("");temp.setText("");note.setText("");media.setText("");refreshLists();});preview.setOnClickListener(v->{ensure();startActivity(new Intent(this,DetailActivity.class).putExtra("id",rid));});clear.setOnClickListener(v->{if(rid>0)new AlertDialog.Builder(this).setTitle("Réinitialiser ?").setMessage("Supprimer tous les ingrédients et étapes ?").setPositiveButton("Oui",(d,w)->{db.clearChildren(rid);refreshLists();}).setNegativeButton("Non",null).show();});del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Supprimer recette ?").setMessage("Cette action supprime aussi les ingrédients et étapes.").setPositiveButton("Supprimer",(d,w)->{db.deleteRecipe(rid);finish();}).setNegativeButton("Annuler",null).show());}
 void saveRecipe(){rid=db.saveRecipe(rid,val(title),val(cat),num(serv,4),num(time,30),val(videos),image,num(rating,0),val(water));}
 void load(){Cursor c=db.one(rid);if(c.moveToFirst()){title.setText(s(c,"title"));cat.setText(s(c,"category"));serv.setText(""+c.getInt(c.getColumnIndexOrThrow("servings")));time.setText(""+c.getInt(c.getColumnIndexOrThrow("time")));videos.setText(s(c,"video"));image=s(c,"image");rating.setText(""+c.getInt(c.getColumnIndexOrThrow("rating")));water.setText(s(c,"water_liters"));if(image!=null&&image.length()>0)photoLabel.setText("📷 Image sélectionnée ✅");}c.close();}
 void refreshLists(){if(ingList==null||stepList==null)return;ingList.removeAllViews();stepList.removeAllViews();if(rid<=0){ingList.addView(UI.smallCard(this,"Enregistre la recette pour voir la liste ici."));stepList.addView(UI.smallCard(this,"Enregistre la recette pour voir les étapes ici."));return;}Cursor i=db.ingredients(rid);int n=0;while(i.moveToNext()){n++;long id=i.getLong(0);TextView row=UI.smallCard(this,"🥕 "+i.getString(2)+"  •  "+i.getString(3)+" "+i.getString(4)+"\nAppui long pour supprimer");row.setOnLongClickListener(v->{db.del("ingredients",id);refreshLists();return true;});ingList.addView(row);}i.close();if(n==0)ingList.addView(UI.smallCard(this,"Aucun ingrédient encore."));Cursor s=db.steps(rid);n=0;while(s.moveToNext()){n++;long id=s.getLong(0);int t=s.getInt(7);TextView row=UI.smallCard(this,"🔥 Étape "+s.getInt(2)+" • "+s.getInt(4)+" min"+(t>0?" • "+t+"°C":"")+"\n"+s.getString(3)+"\n⚠ "+s.getString(6)+"\nAppui long pour supprimer");row.setOnLongClickListener(v->{db.del("steps",id);refreshLists();return true;});stepList.addView(row);}s.close();if(n==0)stepList.addView(UI.smallCard(this,"Aucune étape encore."));}
 void ensure(){if(rid==0)saveRecipe();}
 void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK);}public void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}image=u.toString();photoLabel.setText("📷 Image sélectionnée ✅");}}
 String val(EditText e){return e.getText().toString();}int num(EditText e,int d){try{return (int)Float.parseFloat(val(e).trim().replace(",","."));}catch(Exception x){return d;}}String s(Cursor c,String col){try{String x=c.getString(c.getColumnIndexOrThrow(col));return x==null?"":x;}catch(Exception e){return "";}}}
