package com.recettealarm.app;
import android.Manifest;import android.app.*;import android.content.*;import android.database.*;import android.graphics.Typeface;import android.net.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;
public class MainActivity extends Activity{DB db;LinearLayout root,list,chips;EditText search;String q="",category="Tous";String[] cats={"Tous","Tajines","Gâteaux","Plats","Desserts","Jus","Pain","Autres"};public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},5);askExactAlarm();draw();}public void onResume(){super.onResume();if(list!=null)load();}
 void askExactAlarm(){try{if(Build.VERSION.SDK_INT>=31){android.app.AlarmManager am=(android.app.AlarmManager)getSystemService(ALARM_SERVICE);if(!am.canScheduleExactAlarms())startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM, Uri.parse("package:"+getPackageName())));}}catch(Exception e){}}
 void draw(){root=UI.root(this);LinearLayout top=UI.row(this);TextView h=UI.tv(this,"Recette Alarm",34,Typeface.BOLD);top.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView ic=UI.center(this,"🍳",34,Typeface.BOLD);top.addView(ic);root.addView(top);root.addView(UI.muted(this,"Carnet premium pour cuisiner sans brûler",15));root.addView(UI.hero(this,"⏱️","Mode Anti-Brûlure","Sonnerie forte, vibration, écran allumé et rappel +5 min."));
 LinearLayout stats=UI.row(this);stats.addView(stat("🍽",db.count("recipes"),"recettes"),new LinearLayout.LayoutParams(0,-2,1));stats.addView(stat("🥕",db.count("ingredients"),"ingrédients"),new LinearLayout.LayoutParams(0,-2,1));stats.addView(stat("🔥",db.count("steps"),"étapes"),new LinearLayout.LayoutParams(0,-2,1));root.addView(stats);
 search=UI.input(this,"🔎 Rechercher recette, catégorie...");root.addView(search);search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){q=s.toString().toLowerCase();load();}public void afterTextChanged(android.text.Editable e){}});
 HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);chips=new LinearLayout(this);chips.setOrientation(LinearLayout.HORIZONTAL);hsv.addView(chips);root.addView(hsv);renderChips();
 Button add=UI.btn(this,"+ Nouvelle recette");root.addView(add);add.setOnClickListener(v->startActivity(new Intent(this,EditRecipeActivity.class)));Button shop=UI.whiteBtn(this,"🛒 Liste de courses");root.addView(shop);shop.setOnClickListener(v->share(db.shoppingList()));Button admin=UI.oliveBtn(this,"⚙ Admin / conversions / sauvegarde");root.addView(admin);admin.setOnClickListener(v->startActivity(new Intent(this,AdminActivity.class)));root.addView(UI.tv(this,"Vos recettes",23,Typeface.BOLD));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);load();}
 LinearLayout stat(String icon,int n,String label){LinearLayout b=UI.section(this);b.setPadding(UI.dp(this,8),UI.dp(this,10),UI.dp(this,8),UI.dp(this,10));b.addView(UI.center(this,icon,26,Typeface.BOLD));b.addView(UI.center(this,""+n,22,Typeface.BOLD));b.addView(UI.center(this,label,11,Typeface.NORMAL));return b;}
 void renderChips(){chips.removeAllViews();for(String c:cats){TextView chip=UI.chip(this,c,c.equals(category));chips.addView(chip);chip.setOnClickListener(v->{category=((TextView)v).getText().toString();renderChips();load();});}}
 void load(){list.removeAllViews();Cursor c=db.recipesByCategory(category);int shown=0;while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));String t=s(c,"title"),cat=s(c,"category"),img=s(c,"image");int time=c.getInt(c.getColumnIndexOrThrow("time")),serv=c.getInt(c.getColumnIndexOrThrow("servings")),rating=c.getInt(c.getColumnIndexOrThrow("rating"));String water=s(c,"water_liters");if(q.length()>0&&!t.toLowerCase().contains(q)&&!cat.toLowerCase().contains(q))continue;shown++;LinearLayout card=UI.section(this);card.addView(UI.image(this,img,155));LinearLayout row=UI.row(this);row.addView(UI.tv(this,t,21,Typeface.BOLD),new LinearLayout.LayoutParams(0,-2,1));row.addView(UI.pill(this,cat,UI.terracotta));card.addView(row);card.addView(UI.muted(this,"⏱ "+time+" min   •   👥 "+serv+" pers.   •   "+UI.stars(rating),15));if(water!=null&&water.trim().length()>0)card.addView(UI.muted(this,"💧 "+water,14));card.addView(UI.muted(this,"Appuie pour détail, mode cuisine, modification",13));list.addView(card);card.setOnClickListener(v->startActivity(new Intent(this,DetailActivity.class).putExtra("id",id)));}c.close();if(shown==0)list.addView(UI.smallCard(this,"Aucune recette trouvée. Ajoute une nouvelle recette avec photo, ingrédients et étapes."));}
 String s(Cursor c,String col){try{String x=c.getString(c.getColumnIndexOrThrow(col));return x==null?"":x;}catch(Exception e){return "";}}void share(String s){startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,s),"Partager"));}}
