package com.recettealarm.app;

import android.Manifest;import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import org.json.*;import java.util.*;

public class MainActivity extends Activity{ LinearLayout root; JSONArray recipes=new JSONArray(); int brown=Color.rgb(169,87,47),cream=Color.rgb(255,253,249); String[] cats={"Tous","Tajines","Gâteaux","Plats","Desserts","Jus","Pain","Autres"};
 public void onCreate(Bundle b){super.onCreate(b); reqPerms(); load(); if(recipes.length()==0) seed(); home();}
 void reqPerms(){ if(Build.VERSION.SDK_INT>=33) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},5); }
 TextView tv(String t,int sp,int c,int style){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(c);v.setPadding(24,12,24,8);v.setTypeface(null,style);return v;}
 Button btn(String t){Button b=new Button(this);b.setText(t);b.setTextColor(Color.WHITE);b.setBackgroundColor(brown);b.setAllCaps(false);b.setPadding(12,12,12,12);return b;}
 EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(false);e.setBackgroundColor(Color.WHITE);e.setPadding(20,10,20,10);return e;}
 void base(){ ScrollView sv=new ScrollView(this); root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(cream);sv.addView(root);setContentView(sv);} 
 public void home(){base(); root.addView(tv("Bonjour, Chef ! 👋",16,Color.GRAY,0)); root.addView(tv("Recette Alarm",30,Color.rgb(45,40,38),1)); EditText search=input("Rechercher une recette...");root.addView(search); root.addView(tv("Catégories",20,Color.rgb(45,40,38),1)); HorizontalScrollView hs=new HorizontalScrollView(this); LinearLayout row=new LinearLayout(this);row.setPadding(20,6,20,6); for(String c:cats){Button x=btn(c);x.setOnClickListener(v->showList(c));row.addView(x,new LinearLayout.LayoutParams(-2,90));} hs.addView(row);root.addView(hs); Button add=btn("Nouvelle Recette");add.setOnClickListener(v->addRecipe());root.addView(add,new LinearLayout.LayoutParams(-1,100)); Button admin=btn("Administration & Paramètres");admin.setOnClickListener(v->admin());root.addView(admin,new LinearLayout.LayoutParams(-1,100)); showList("Tous");}
 void showList(String cat){ if(root.getTag()!=null) root.removeView((View)root.getTag()); LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.addView(tv("Vos Recettes",22,Color.rgb(45,40,38),1)); for(int i=0;i<recipes.length();i++){try{JSONObject r=recipes.getJSONObject(i); if(!cat.equals("Tous")&&!r.optString("category").equals(cat))continue; Button card=btn(r.optString("title")+"\n"+r.optString("category")+" • "+r.optInt("time")+" min • "+r.optInt("servings")+" pers."); final int ix=i; card.setOnClickListener(v->detail(ix)); list.addView(card,new LinearLayout.LayoutParams(-1,130));}catch(Exception e){}} root.addView(list); root.setTag(list);}
 void addRecipe(){base(); root.addView(tv("← Nouvelle Recette",26,Color.rgb(45,40,38),1)); EditText title=input("Nom de la recette"); EditText cat=input("Catégorie: Tajines, Gâteaux..."); EditText pers=input("Nombre de personnes"); EditText time=input("Temps total en minutes"); EditText video=input("Lien vidéo optionnel"); root.addView(title);root.addView(cat);root.addView(pers);root.addView(time);root.addView(video); Button save=btn("Enregistrer la recette"); root.addView(save,new LinearLayout.LayoutParams(-1,100)); save.setOnClickListener(v->{try{JSONObject r=new JSONObject();r.put("title",title.getText().toString());r.put("category",cat.getText().toString().isEmpty()?"Plats":cat.getText().toString());r.put("servings",num(pers,4));r.put("time",num(time,30));r.put("video",video.getText().toString());r.put("ingredients",new JSONArray());r.put("steps",new JSONArray());recipes.put(r);save();detail(recipes.length()-1);}catch(Exception e){toast(e.toString());}});}
 int num(EditText e,int d){try{return Integer.parseInt(e.getText().toString().trim());}catch(Exception x){return d;}}
 void detail(int ix){base(); try{JSONObject r=recipes.getJSONObject(ix); root.addView(tv("← "+r.optString("title"),25,Color.rgb(45,40,38),1)); root.addView(tv(r.optString("category")+" • "+r.optInt("time")+" min • "+r.optInt("servings")+" pers.",16,Color.GRAY,0)); Button ing=btn("Gérer les ingrédients");ing.setOnClickListener(v->ingredients(ix));root.addView(ing); Button st=btn("Gérer les étapes & alarmes");st.setOnClickListener(v->steps(ix));root.addView(st); Button cook=btn("Démarrer la Cuisine");cook.setOnClickListener(v->cook(ix,0));root.addView(cook,new LinearLayout.LayoutParams(-1,110)); root.addView(tv("Ingrédients",22,Color.rgb(45,40,38),1)); JSONArray a=r.getJSONArray("ingredients"); for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);root.addView(tv("• "+o.optString("name")+" — "+o.optString("qty")+" "+o.optString("unit"),16,Color.DKGRAY,0));} root.addView(tv("Étapes",22,Color.rgb(45,40,38),1)); JSONArray s=r.getJSONArray("steps"); for(int i=0;i<s.length();i++){JSONObject o=s.getJSONObject(i);root.addView(tv((i+1)+". "+o.optString("desc")+" — "+o.optInt("min")+" min 🔔",16,Color.DKGRAY,0));} }catch(Exception e){toast(e.toString());}}
 void ingredients(int ix){base(); root.addView(tv("← Ingrédients",26,Color.rgb(45,40,38),1)); EditText name=input("Ex: Farine, huile...");EditText qty=input("Quantité");EditText unit=input("Unité: g, kg, ml, litre, verre, cs, cc, pièce");root.addView(name);root.addView(qty);root.addView(unit); Button add=btn("Ajouter à la liste");root.addView(add); add.setOnClickListener(v->{try{JSONObject o=new JSONObject();o.put("name",name.getText());o.put("qty",qty.getText());o.put("unit",unit.getText());recipes.getJSONObject(ix).getJSONArray("ingredients").put(o);save();ingredients(ix);}catch(Exception e){}}); Button done=btn("Enregistrer et revenir");done.setOnClickListener(v->detail(ix));root.addView(done);}
 void steps(int ix){base(); root.addView(tv("← Nouvelle Étape",26,Color.rgb(45,40,38),1)); EditText desc=input("Description de l'action");EditText min=input("Durée minutes");EditText note=input("Note sécurité anti-brûlure");root.addView(desc);root.addView(min);root.addView(note); Button add=btn("Ajouter l'étape avec alarme");root.addView(add);add.setOnClickListener(v->{try{JSONObject o=new JSONObject();o.put("desc",desc.getText());o.put("min",num(min,5));o.put("note",note.getText());o.put("alarm",true);recipes.getJSONObject(ix).getJSONArray("steps").put(o);save();steps(ix);}catch(Exception e){}}); Button done=btn("Terminer");done.setOnClickListener(v->detail(ix));root.addView(done);}
 void cook(int ix,int step){base();try{JSONObject r=recipes.getJSONObject(ix);JSONArray s=r.getJSONArray("steps"); if(s.length()==0){toast("Ajoute au moins une étape");detail(ix);return;} if(step>=s.length()){root.addView(tv("Recette terminée ✅",30,Color.rgb(45,40,38),1));Button h=btn("Retour accueil");h.setOnClickListener(v->home());root.addView(h);return;} JSONObject o=s.getJSONObject(step); root.addView(tv(r.optString("title"),22,Color.rgb(45,40,38),1)); root.addView(tv("Étape "+(step+1)+" sur "+s.length(),16,Color.GRAY,0)); TextView big=tv(String.format(Locale.FRANCE,"%02d:00",o.optInt("min")),62,Color.rgb(45,40,38),1);root.addView(big); root.addView(tv(o.optString("desc"),24,Color.rgb(45,40,38),1)); root.addView(tv("⚠️ Note : "+o.optString("note"),18,Color.rgb(230,80,30),1)); Button start=btn("Démarrer l'alarme");root.addView(start,new LinearLayout.LayoutParams(-1,110)); start.setOnClickListener(v->{schedule(ix,step,o.optInt("min"),r.optString("title"),o.optString("note"));toast("Alarme programmée");}); Button next=btn("Étape suivante");next.setOnClickListener(v->cook(ix,step+1));root.addView(next);}catch(Exception e){toast(e.toString());}}
 void schedule(int ix,int st,int minutes,String title,String note){Intent in=new Intent(this,AlarmReceiver.class);in.putExtra("title",title);in.putExtra("note",note);in.putExtra("ix",ix);in.putExtra("st",st);PendingIntent pi=PendingIntent.getBroadcast(this,ix*100+st,in,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);long t=System.currentTimeMillis()+minutes*60000L; if(Build.VERSION.SDK_INT>=23)am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,t,pi); else am.setExact(AlarmManager.RTC_WAKEUP,t,pi);}
 void admin(){base();root.addView(tv("Administration",28,Color.rgb(45,40,38),1));root.addView(tv("Gestion incluse : catégories, unités, sauvegarde locale, import/export JSON, alarmes, vibrations, mode anti-brûlure.",16,Color.DKGRAY,0)); Button export=btn("Exporter les données JSON");export.setOnClickListener(v->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("recettes",recipes.toString()));toast("JSON copié");});root.addView(export); Button reset=btn("Réinitialiser exemples");reset.setOnClickListener(v->{recipes=new JSONArray();seed();home();});root.addView(reset);}
 void seed(){try{JSONObject r=new JSONObject();r.put("title","Tajine Poulet aux Olives");r.put("category","Tajines");r.put("servings",4);r.put("time",45);r.put("video","");r.put("ingredients",new JSONArray("[{\"name\":\"Poulet fermier\",\"qty\":\"1.5\",\"unit\":\"kg\"},{\"name\":\"Olives vertes\",\"qty\":\"1\",\"unit\":\"verre\"}]") );r.put("steps",new JSONArray("[{\"desc\":\"Faire revenir le poulet\",\"min\":1,\"note\":\"Baisser le feu et remuer immédiatement\",\"alarm\":true}]") );recipes.put(r);save();}catch(Exception e){}}
 void load(){try{recipes=new JSONArray(getSharedPreferences("db",0).getString("recipes","[]"));}catch(Exception e){recipes=new JSONArray();}}
 void save(){getSharedPreferences("db",0).edit().putString("recipes",recipes.toString()).apply();}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 public void onBackPressed(){home();}
}
