package com.recettealarm.app;
import android.Manifest;import android.app.*;import android.content.*;import android.database.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.ColorDrawable;import android.net.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{DB db;LinearLayout root,list,chips;EditText search;String q="",category="Tous";String[] cats={"Tous","Tajines","Gâteaux","Plats","Desserts","Jus","Pain","Autres"};TextView statRecipes,statFav,statTime;
 public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},5);askExactAlarm();draw();}
 public void onResume(){super.onResume();if(list!=null){load();renderStats();}}
 void askExactAlarm(){try{if(Build.VERSION.SDK_INT>=31){AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);if(!am.canScheduleExactAlarms())startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM, Uri.parse("package:"+getPackageName())));}}catch(Exception e){}}
 void draw(){root=UI.root(this);root.setPadding(UI.dp(this,16),UI.dp(this,20),UI.dp(this,16),UI.dp(this,90));
  LinearLayout top=UI.row(this);TextView menu=UI.iconBtn(this,"☰");TextView bell=UI.iconBtn(this,"🔔");top.addView(menu);TextView hello=UI.tv(this,"Bonjour Chef 👋\nQue cuisine-t-on aujourd'hui ?",26,Typeface.BOLD);hello.setPadding(UI.dp(this,6),0,0,0);top.addView(hello,new LinearLayout.LayoutParams(0,-2,1));top.addView(bell);root.addView(top);menu.setOnClickListener(v->openMenu());bell.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));
  root.addView(UI.glassHero(this,"Cuisine intelligente","Alarmes anti-brûlure, courses et conversions en une seule app."));
  search=UI.input(this,"🔎 Rechercher recette, ingrédient...");root.addView(search);search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){q=s.toString().toLowerCase();load();}public void afterTextChanged(android.text.Editable e){}});
  LinearLayout quick=UI.row(this);TextView scan=UI.chip(this,"📷 Scan",false),course=UI.chip(this,"🛒 Courses",false),conv=UI.chip(this,"📐 Mesures",false);quick.addView(scan,new LinearLayout.LayoutParams(0,-2,1));quick.addView(course,new LinearLayout.LayoutParams(0,-2,1));quick.addView(conv,new LinearLayout.LayoutParams(0,-2,1));root.addView(quick);scan.setOnClickListener(v->UI.toast(this,"Scan ingrédients prévu en prochaine version"));course.setOnClickListener(v->startActivity(new Intent(this,ShoppingActivity.class)));conv.setOnClickListener(v->showText("Convertisseur",db.conversions()));
  LinearLayout catHead=UI.row(this);catHead.addView(UI.tv(this,"Catégories",22,Typeface.BOLD),new LinearLayout.LayoutParams(0,-2,1));TextView all=UI.tv(this,"Voir tout",15,Typeface.BOLD);all.setTextColor(UI.green);catHead.addView(all);root.addView(catHead);all.setOnClickListener(v->{category="Tous";renderChips();load();});HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);chips=new LinearLayout(this);chips.setOrientation(LinearLayout.HORIZONTAL);hsv.addView(chips);root.addView(hsv);renderChips();
  LinearLayout stats=UI.row(this);statRecipes=UI.metric(this,"🍽","0","Recettes");statFav=UI.metric(this,"❤️","0","Favoris");statTime=UI.metric(this,"⏱","0h","Temps");stats.addView(statRecipes,new LinearLayout.LayoutParams(0,-2,1));stats.addView(statFav,new LinearLayout.LayoutParams(0,-2,1));stats.addView(statTime,new LinearLayout.LayoutParams(0,-2,1));root.addView(stats);renderStats();
  LinearLayout titleRow=UI.row(this);titleRow.addView(UI.tv(this,"Recettes populaires",23,Typeface.BOLD),new LinearLayout.LayoutParams(0,-2,1));TextView addTop=UI.chip(this,"＋",true);titleRow.addView(addTop);root.addView(titleRow);addTop.setOnClickListener(v->startActivity(new Intent(this,EditRecipeActivity.class)));
  list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);load();
  LinearLayout nav=UI.bottomNav(this);TextView n1=UI.navItem(this,"🏠\nAccueil"),n2=UI.navItem(this,"🛒\nCourses"),n3=UI.navItem(this,"＋\nAjouter"),n4=UI.navItem(this,"⚙️\nRéglages");nav.addView(n1,new LinearLayout.LayoutParams(0,-2,1));nav.addView(n2,new LinearLayout.LayoutParams(0,-2,1));nav.addView(n3,new LinearLayout.LayoutParams(0,-2,1));nav.addView(n4,new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);n2.setOnClickListener(v->startActivity(new Intent(this,ShoppingActivity.class)));n3.setOnClickListener(v->startActivity(new Intent(this,EditRecipeActivity.class)));n4.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));
 }
 void renderStats(){if(statRecipes==null)return;int r=db.count("recipes"),fav=0,total=0;Cursor c=db.recipes();while(c.moveToNext()){try{fav+=c.getInt(c.getColumnIndexOrThrow("fav"))==1?1:0;total+=c.getInt(c.getColumnIndexOrThrow("time"));}catch(Exception e){}}c.close();statRecipes.setText("🍽\n"+r+"\nRecettes");statFav.setText("❤️\n"+fav+"\nFavoris");statTime.setText("⏱\n"+(total/60)+"h"+(total%60)+"\nTemps");}
 void renderChips(){chips.removeAllViews();for(String c:cats){TextView chip=UI.chip(this,iconFor(c)+" "+c,c.equals(category));chip.setOnClickListener(v->{category=c;renderChips();load();});chips.addView(chip);}}
 String iconFor(String c){if(c.equals("Tajines"))return "🥘";if(c.equals("Gâteaux"))return "🍰";if(c.equals("Jus"))return "🥤";if(c.equals("Desserts"))return "🍮";if(c.equals("Pain"))return "🥖";if(c.equals("Plats"))return "🍽";return "🔥";}
 void load(){if(list==null)return;list.removeAllViews();Cursor c=db.recipesByCategory(category);ArrayList<long[]> ids=new ArrayList<>();ArrayList<String[]> data=new ArrayList<>();while(c.moveToNext()){String title=s(c,"title"),cat=s(c,"category"),img=s(c,"image");int time=c.getInt(c.getColumnIndexOrThrow("time")),serv=c.getInt(c.getColumnIndexOrThrow("servings")),rating=c.getInt(c.getColumnIndexOrThrow("rating"));if(q.length()>0&&!(title.toLowerCase().contains(q)||cat.toLowerCase().contains(q)))continue;ids.add(new long[]{c.getLong(c.getColumnIndexOrThrow("id")),time,serv,rating});data.add(new String[]{title,cat,img});}c.close();if(ids.size()==0){list.addView(UI.smallCard(this,"Aucune recette. Clique sur ＋ Ajouter."));return;}for(int i=0;i<ids.size();i+=2){LinearLayout row=UI.row(this);row.setGravity(Gravity.TOP);row.addView(recipeCard(ids.get(i),data.get(i)),new LinearLayout.LayoutParams(0,-2,1));if(i+1<ids.size())row.addView(recipeCard(ids.get(i+1),data.get(i+1)),new LinearLayout.LayoutParams(0,-2,1));else row.addView(new Space(this),new LinearLayout.LayoutParams(0,1,1));list.addView(row);}}
 View recipeCard(long[] meta,String[] d){long id=meta[0];int time=(int)meta[1],serv=(int)meta[2],rating=(int)meta[3];LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackground(UI.stroke(this,Color.WHITE,UI.dp(this,30),0xffe4e7df));card.setPadding(0,0,0,UI.dp(this,10));LinearLayout.LayoutParams clp=new LinearLayout.LayoutParams(-1,-2);clp.setMargins(UI.dp(this,5),UI.dp(this,6),UI.dp(this,5),UI.dp(this,14));card.setLayoutParams(clp);FrameLayout hero=UI.foodHero(this,d[2],138,iconFor(d[1]),shorten(d[0]));card.addView(hero);LinearLayout over=UI.row(this);over.setPadding(UI.dp(this,10),0,UI.dp(this,10),0);over.addView(UI.pill(this,"⏱ "+time+" min",UI.green),new LinearLayout.LayoutParams(0,-2,1));TextView fav=UI.center(this,"♡",25,Typeface.BOLD);fav.setTextColor(0xffd01818);over.addView(fav);card.addView(over);TextView cat=UI.tv(this,d[1],12,Typeface.BOLD);cat.setTextColor(UI.green);cat.setPadding(UI.dp(this,12),0,0,0);card.addView(cat);TextView title=UI.tv(this,shorten(d[0]),17,Typeface.BOLD);title.setPadding(UI.dp(this,12),0,UI.dp(this,8),0);card.addView(title);TextView metaTxt=UI.muted(this,"👥 "+serv+" pers.   ⭐ "+rating+"/5",13);metaTxt.setPadding(UI.dp(this,12),0,0,0);card.addView(metaTxt);card.setOnClickListener(v->startActivity(new Intent(this,DetailActivity.class).putExtra("id",id)));return card;}
 String shorten(String s){return s==null?"Recette":s.length()>20?s.substring(0,20)+"...":s;}
 void openMenu(){Dialog dialog=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(UI.dp(this,22),UI.dp(this,18),UI.dp(this,22),UI.dp(this,22));box.setBackground(UI.stroke(this,Color.WHITE,UI.dp(this,30),0xffe2e5df));box.addView(UI.tv(this,"Menu Recette Alarm",24,Typeface.BOLD));addMenuItem(box,"🍽  Toutes les recettes",()->{category="Tous";renderChips();load();dialog.dismiss();});addMenuItem(box,"❤️  Favoris",()->{dialog.dismiss();startActivity(new Intent(this,FavoritesActivity.class));});addMenuItem(box,"🛒  Liste de courses",()->{dialog.dismiss();startActivity(new Intent(this,ShoppingActivity.class));});addMenuItem(box,"📐  Convertisseur mesures",()->{dialog.dismiss();showText("Convertisseur",db.conversions());});addMenuItem(box,"⏱  Mode cuisine test",()->{dialog.dismiss();startActivity(new Intent(this,CookingActivity.class));});addMenuItem(box,"⚙️  Paramètres",()->{dialog.dismiss();startActivity(new Intent(this,SettingsActivity.class));});addMenuItem(box,"🛠  Admin",()->{dialog.dismiss();startActivity(new Intent(this,AdminActivity.class));});addMenuItem(box,"＋  Nouvelle recette",()->{dialog.dismiss();startActivity(new Intent(this,EditRecipeActivity.class));});dialog.setContentView(box);Window w=dialog.getWindow();dialog.show();w=dialog.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));WindowManager.LayoutParams p=w.getAttributes();p.width=WindowManager.LayoutParams.MATCH_PARENT;p.height=WindowManager.LayoutParams.WRAP_CONTENT;p.gravity=Gravity.BOTTOM;w.setAttributes(p);} }
 void addMenuItem(LinearLayout box,String text,final Runnable r){TextView v=UI.tv(this,text,18,Typeface.BOLD);v.setPadding(0,UI.dp(this,14),0,UI.dp(this,14));v.setOnClickListener(x->r.run());box.addView(v,new LinearLayout.LayoutParams(-1,-2));}
 void showText(String title,String msg){new AlertDialog.Builder(this).setTitle(title).setMessage(msg).setPositiveButton("OK",null).show();}String s(Cursor c,String col){try{String x=c.getString(c.getColumnIndexOrThrow(col));return x==null?"":x;}catch(Exception e){return "";}}
}
