package com.recettealarm.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.*;import android.text.InputType;import android.view.*;import android.widget.*;

public class UI{
 static int bg=Color.rgb(248,246,240),surface=Color.WHITE,soft=Color.rgb(241,244,238),dark=Color.rgb(18,22,21),muted=Color.rgb(116,121,117);
 static int primary=Color.rgb(14,79,79),primary2=Color.rgb(7,58,55),accent=Color.rgb(246,198,91),accent2=Color.rgb(255,232,164),danger=Color.rgb(202,52,48),gold=Color.rgb(242,179,49);
 static int lime=accent,lime2=accent2,green=primary,green2=primary2,card=surface,cream=bg;
 static int dp(Context c,int v){return (int)(v*c.getResources().getDisplayMetrics().density+0.5f);}static GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);return g;}static GradientDrawable stroke(Context c,int color,int radius,int sc){GradientDrawable g=bg(color,radius);g.setStroke(dp(c,1),sc);return g;}static GradientDrawable grad(int c1,int c2,int radius){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{c1,c2});g.setCornerRadius(radius);return g;}
 static void elev(View v,int e){if(android.os.Build.VERSION.SDK_INT>=21)v.setElevation(dp(v.getContext(),e));}
 static TextView tv(Context c,String t,int sp,int style){TextView v=new TextView(c);v.setText(t==null?"":t);v.setTextSize(sp);v.setTypeface(Typeface.DEFAULT,style);v.setTextColor(dark);v.setPadding(dp(c,2),dp(c,3),dp(c,2),dp(c,3));v.setLineSpacing(dp(c,2),1.03f);return v;}static TextView muted(Context c,String t,int sp){TextView v=tv(c,t,sp,Typeface.NORMAL);v.setTextColor(muted);return v;}static TextView center(Context c,String t,int sp,int style){TextView v=tv(c,t,sp,style);v.setGravity(Gravity.CENTER);return v;}
 static Button btn(Context c,String t){Button b=new Button(c);b.setText(t);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setPadding(dp(c,14),dp(c,8),dp(c,14),dp(c,8));b.setBackground(grad(primary,primary2,dp(c,26)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(c,52));lp.setMargins(0,dp(c,6),0,dp(c,7));b.setLayoutParams(lp);elev(b,3);return b;}static Button limeBtn(Context c,String t){Button b=btn(c,t);b.setTextColor(dark);b.setBackground(grad(accent,accent2,dp(c,28)));return b;}static Button whiteBtn(Context c,String t){Button b=btn(c,t);b.setTextColor(dark);b.setBackground(stroke(c,Color.WHITE,dp(c,26),Color.rgb(231,229,221)));elev(b,1);return b;}static Button dangerBtn(Context c,String t){Button b=btn(c,t);b.setBackground(grad(danger,Color.rgb(226,87,69),dp(c,28)));return b;}static Button oliveBtn(Context c,String t){return limeBtn(c,t);}
 static EditText input(Context c,String h){EditText e=new EditText(c);e.setHint(h);e.setTextSize(15);e.setTextColor(dark);e.setHintTextColor(Color.rgb(154,158,154));e.setSingleLine(false);e.setMinLines(1);e.setPadding(dp(c,16),dp(c,12),dp(c,16),dp(c,12));e.setBackground(stroke(c,Color.WHITE,dp(c,24),Color.rgb(231,229,221)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(c,5),0,dp(c,8));e.setLayoutParams(lp);return e;}static EditText area(Context c,String h){EditText e=input(c,h);e.setMinLines(3);e.setGravity(Gravity.TOP);return e;}static EditText number(Context c,String h){EditText e=input(c,h);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}
 static LinearLayout root(Activity a){ScrollView sv=new ScrollView(a);sv.setFillViewport(true);LinearLayout l=new LinearLayout(a);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(a,18),dp(a,18),dp(a,18),dp(a,26));l.setBackgroundColor(bg);sv.addView(l,new ScrollView.LayoutParams(-1,-2));a.setContentView(sv);return l;}static LinearLayout row(Context c){LinearLayout l=new LinearLayout(c);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}static LinearLayout section(Context c){LinearLayout box=new LinearLayout(c);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(c,16),dp(c,14),dp(c,16),dp(c,14));box.setBackground(stroke(c,surface,dp(c,28),Color.rgb(233,231,224)));elev(box,1);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(c,8),0,dp(c,12));box.setLayoutParams(lp);return box;}
 static LinearLayout glassHero(Context c,String title,String sub){LinearLayout h=new LinearLayout(c);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(c,20),dp(c,18),dp(c,18),dp(c,18));h.setBackground(grad(Color.rgb(255,248,220),Color.rgb(239,248,240),dp(c,34)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(c,7),0,dp(c,14));h.setLayoutParams(lp);elev(h,1);TextView a=tv(c,title,27,Typeface.BOLD);h.addView(a);TextView s=muted(c,sub,15);s.setPadding(dp(c,3),dp(c,5),dp(c,3),0);h.addView(s);return h;}static LinearLayout hero(Context c,String icon,String title,String sub){return glassHero(c,icon+"  "+title,sub);}
 static TextView chip(Context c,String t,boolean active){TextView v=center(c,t,13,Typeface.BOLD);v.setTextColor(active?Color.WHITE:dark);v.setBackground(active?grad(primary,primary2,dp(c,36)):stroke(c,Color.WHITE,dp(c,36),Color.rgb(231,229,221)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(c,44));lp.setMargins(0,dp(c,4),dp(c,8),dp(c,6));v.setMinWidth(dp(c,82));v.setGravity(Gravity.CENTER);v.setLayoutParams(lp);return v;}static TextView card(Context c,String t){TextView v=tv(c,t,16,Typeface.BOLD);v.setBackground(stroke(c,Color.WHITE,dp(c,24),Color.rgb(232,230,223)));v.setPadding(dp(c,16),dp(c,14),dp(c,16),dp(c,14));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(c,6),0,dp(c,8));v.setLayoutParams(lp);elev(v,1);return v;}static TextView smallCard(Context c,String t){TextView v=card(c,t);v.setTextSize(15);v.setTypeface(Typeface.DEFAULT,Typeface.NORMAL);return v;}
 static TextView iconBtn(Context c,String t){TextView v=center(c,t,24,Typeface.BOLD);v.setTextColor(dark);v.setBackground(stroke(c,Color.WHITE,dp(c,20),Color.rgb(232,230,223)));v.setGravity(Gravity.CENTER);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(c,54),dp(c,54));lp.setMargins(0,0,dp(c,8),dp(c,8));v.setLayoutParams(lp);elev(v,2);return v;}static TextView pill(Context c,String t,int color){TextView v=center(c,t,12,Typeface.BOLD);v.setTextColor(Color.WHITE);v.setBackground(bg(color,dp(c,24)));v.setPadding(dp(c,11),dp(c,6),dp(c,11),dp(c,6));return v;}
 static ImageView image(Context c,String uri,int h){ImageView iv=new ImageView(c);iv.setScaleType(ImageView.ScaleType.CENTER_CROP);iv.setBackground(grad(Color.rgb(255,248,230),Color.rgb(238,248,240),dp(c,28)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(c,h));lp.setMargins(0,dp(c,6),0,dp(c,8));iv.setLayoutParams(lp);try{if(uri!=null&&uri.trim().length()>0)iv.setImageURI(Uri.parse(uri));else iv.setImageDrawable(null);}catch(Exception e){iv.setImageDrawable(null);}return iv;}
 static FrameLayout foodHero(Context c,String uri,int h,String emoji,String title){FrameLayout f=new FrameLayout(c);f.setBackground(grad(Color.rgb(255,248,230),Color.rgb(238,248,240),dp(c,30)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(c,h));lp.setMargins(0,dp(c,4),0,dp(c,9));f.setLayoutParams(lp);elev(f,2);if(uri!=null&&uri.trim().length()>0){ImageView img=image(c,uri,h);img.setLayoutParams(new FrameLayout.LayoutParams(-1,-1));f.addView(img);}else{FoodArtView art=new FoodArtView(c);art.setData(emoji,title);f.addView(art,new FrameLayout.LayoutParams(-1,-1));}return f;}
 static TextView navItem(Context c,String t){TextView v=center(c,t,12,Typeface.BOLD);v.setTextColor(dark);v.setPadding(dp(c,6),dp(c,7),dp(c,6),dp(c,7));return v;}static LinearLayout bottomNav(Context c){LinearLayout n=row(c);n.setGravity(Gravity.CENTER);n.setPadding(dp(c,8),dp(c,6),dp(c,8),dp(c,6));n.setBackground(stroke(c,Color.WHITE,dp(c,26),Color.rgb(231,229,221)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(c,10),0,dp(c,10));n.setLayoutParams(lp);elev(n,5);return n;}
 static TextView metric(Context c,String icon,String value,String label){TextView v=center(c,icon+"\n"+value+"\n"+label,12,Typeface.BOLD);v.setBackground(stroke(c,Color.WHITE,dp(c,22),Color.rgb(232,230,223)));v.setPadding(0,dp(c,9),0,dp(c,9));elev(v,1);return v;}
 static String stars(int r){if(r<0)r=0;if(r>5)r=5;String s="";for(int i=1;i<=5;i++)s+=i<=r?"★":"☆";return s;}static void toast(Context c,String s){Toast.makeText(c,s,Toast.LENGTH_SHORT).show();}
}
